import type { TradeGoodDefinition } from "../../domain/trade-good";

export const globalGoodsPool: TradeGoodDefinition[] = [
  {
    id: "rice",
    name: "米",
    category: "grain",
    shopType: "grain-shop",
    rarity: "common",
    basePrice: 100,
    minPrice: 60,
    maxPrice: 180,
    unit: "石",
    originTags: ["agriculture", "jiangnan"],
    demandTags: ["city", "famine"],
    description: "江南常见主粮。",
  },
  {
    id: "wheat",
    name: "麦",
    category: "grain",
    shopType: "grain-shop",
    rarity: "common",
    basePrice: 90,
    minPrice: 55,
    maxPrice: 160,
    unit: "石",
    originTags: ["agriculture", "northern"],
    demandTags: ["city", "military"],
    description: "北地常见粮食，可磨面制食。",
  },
  {
    id: "salt",
    name: "盐",
    category: "grain",
    shopType: "grain-shop",
    rarity: "common",
    basePrice: 120,
    minPrice: 70,
    maxPrice: 220,
    unit: "担",
    originTags: ["maritime", "commercial"],
    demandTags: ["city", "famine"],
    description: "民生所需，也常受官府管控。",
  },
  {
    id: "soybean",
    name: "黄豆",
    category: "grain",
    shopType: "grain-shop",
    rarity: "common",
    basePrice: 85,
    minPrice: 50,
    maxPrice: 140,
    unit: "石",
    originTags: ["agriculture"],
    demandTags: ["city", "commercial"],
    description: "可食可榨，是常见的杂粮货物。",
  },
  {
    id: "millet",
    name: "粟米",
    category: "grain",
    shopType: "grain-shop",
    rarity: "common",
    basePrice: 80,
    minPrice: 45,
    maxPrice: 135,
    unit: "石",
    originTags: ["agriculture", "northern"],
    demandTags: ["military", "famine"],
    description: "耐储存，常为边地与军中所用。",
  },
  {
    id: "ginseng",
    name: "人参",
    category: "medicine",
    shopType: "medicine-shop",
    rarity: "rare",
    basePrice: 420,
    minPrice: 280,
    maxPrice: 760,
    unit: "斤",
    originTags: ["forest", "northern"],
    demandTags: ["rich-city", "clinic"],
    description: "昂贵的补气药材，多为权贵与富户所需。",
  },
  {
    id: "herbs",
    name: "草药",
    category: "medicine",
    shopType: "medicine-shop",
    rarity: "common",
    basePrice: 110,
    minPrice: 70,
    maxPrice: 180,
    unit: "包",
    originTags: ["forest"],
    demandTags: ["clinic", "famine"],
    description: "常见草药，走乡郎中也常贩售。",
  },
  {
    id: "silk",
    name: "丝绸",
    category: "silk",
    shopType: "silk-shop",
    rarity: "rare",
    basePrice: 450,
    minPrice: 300,
    maxPrice: 900,
    unit: "匹",
    originTags: ["jiangnan", "commercial"],
    demandTags: ["rich-city", "large-city"],
    description: "江南织造的上等丝绸。",
  },
  {
    id: "tea",
    name: "茶叶",
    category: "silk",
    shopType: "silk-shop",
    rarity: "uncommon",
    basePrice: 210,
    minPrice: 140,
    maxPrice: 360,
    unit: "斤",
    originTags: ["jiangnan", "forest"],
    demandTags: ["commercial", "large-city"],
    description: "名山新茶，文士与商人都爱品饮。",
  },
  {
    id: "ironware",
    name: "铁器",
    category: "arms",
    shopType: "smithy",
    rarity: "common",
    basePrice: 190,
    minPrice: 120,
    maxPrice: 320,
    unit: "件",
    originTags: ["mine", "northern"],
    demandTags: ["military", "border-city"],
    description: "刀具农具皆可归入其列，是军民皆需的货物。",
  },
  {
    id: "warhorse",
    name: "战马",
    category: "horses",
    shopType: "horse-market",
    rarity: "rare",
    basePrice: 800,
    minPrice: 500,
    maxPrice: 1500,
    unit: "匹",
    originTags: ["grassland"],
    demandTags: ["war", "military"],
    description: "北地军马，适合骑战。",
  },
  {
    id: "antique",
    name: "古董",
    category: "special",
    shopType: "general-store",
    rarity: "rare",
    basePrice: 600,
    minPrice: 360,
    maxPrice: 1100,
    unit: "件",
    originTags: ["large-city", "old-capital"],
    demandTags: ["rich-city"],
    description: "来路复杂的旧器玩物，识货者愿出高价。",
  },
];
