import type { TradeGoodDefinition } from "../../domain/trade-good";

export const globalGoodsPool: TradeGoodDefinition[] = [
  {
    id: "rice",
    name: "米",
    category: "粮食",
    shopType: "grain-shop",
    rarity: "common",
    basePrice: 100,
    minPrice: 60,
    maxPrice: 180,
    unit: "石",
    originTags: ["农业", "江南"],
    demandTags: ["城市", "灾荒"],
    description: "江南常见主粮。",
  },
  {
    id: "wheat",
    name: "麦",
    category: "粮食",
    shopType: "grain-shop",
    rarity: "common",
    basePrice: 90,
    minPrice: 55,
    maxPrice: 160,
    unit: "石",
    originTags: ["农业", "北地"],
    demandTags: ["城市", "军需"],
    description: "北方常见粮食，可磨面制食。",
  },
  {
    id: "salt",
    name: "盐",
    category: "粮食",
    shopType: "grain-shop",
    rarity: "common",
    basePrice: 120,
    minPrice: 70,
    maxPrice: 220,
    unit: "担",
    originTags: ["海贸", "商业"],
    demandTags: ["城市", "灾荒"],
    description: "民生所需，亦常受官府管控。",
  },
  {
    id: "soybean",
    name: "黄豆",
    category: "粮食",
    shopType: "grain-shop",
    rarity: "common",
    basePrice: 85,
    minPrice: 50,
    maxPrice: 140,
    unit: "石",
    originTags: ["农业"],
    demandTags: ["城市", "商贸"],
    description: "可食可榨，是常见的杂粮货物。",
  },
  {
    id: "millet",
    name: "粟米",
    category: "粮食",
    shopType: "grain-shop",
    rarity: "common",
    basePrice: 80,
    minPrice: 45,
    maxPrice: 135,
    unit: "石",
    originTags: ["农业", "北地"],
    demandTags: ["军需", "灾荒"],
    description: "耐储存，常为边地与军中所用。",
  },
  {
    id: "ginseng",
    name: "人参",
    category: "药材",
    shopType: "medicine-shop",
    rarity: "rare",
    basePrice: 420,
    minPrice: 280,
    maxPrice: 760,
    unit: "斤",
    originTags: ["山林", "北地"],
    demandTags: ["富城", "医馆"],
    description: "昂贵的补气药材，多为权贵与富户所需。",
  },
  {
    id: "herbs",
    name: "草药",
    category: "药材",
    shopType: "medicine-shop",
    rarity: "common",
    basePrice: 110,
    minPrice: 70,
    maxPrice: 180,
    unit: "包",
    originTags: ["山林"],
    demandTags: ["医馆", "灾荒"],
    description: "常见草药，走乡郎中也常贩售。",
  },
  {
    id: "deer-antler",
    name: "鹿茸",
    category: "药材",
    shopType: "medicine-shop",
    rarity: "rare",
    basePrice: 360,
    minPrice: 240,
    maxPrice: 620,
    unit: "两",
    originTags: ["山林"],
    demandTags: ["富城", "医馆"],
    description: "珍贵药材，多从山林猎获而来。",
  },
  {
    id: "mugwort",
    name: "艾草",
    category: "药材",
    shopType: "medicine-shop",
    rarity: "common",
    basePrice: 70,
    minPrice: 40,
    maxPrice: 120,
    unit: "束",
    originTags: ["农业"],
    demandTags: ["城市", "医馆"],
    description: "民间常见药草，可入药也可驱湿。",
  },
  {
    id: "angelica",
    name: "当归",
    category: "药材",
    shopType: "medicine-shop",
    rarity: "uncommon",
    basePrice: 160,
    minPrice: 100,
    maxPrice: 280,
    unit: "斤",
    originTags: ["山林", "北地"],
    demandTags: ["医馆", "富城"],
    description: "常见补养药材，在城中药铺颇有销路。",
  },
  {
    id: "silk",
    name: "丝绸",
    category: "绸缎",
    shopType: "silk-shop",
    rarity: "rare",
    basePrice: 450,
    minPrice: 300,
    maxPrice: 900,
    unit: "匹",
    originTags: ["江南", "商业"],
    demandTags: ["富城", "大城"],
    description: "江南织造的上等丝绸。",
  },
  {
    id: "tea",
    name: "茶叶",
    category: "绸缎",
    shopType: "silk-shop",
    rarity: "uncommon",
    basePrice: 210,
    minPrice: 140,
    maxPrice: 360,
    unit: "斤",
    originTags: ["江南", "山林"],
    demandTags: ["商业", "大城"],
    description: "名山新茶，文士与商人都爱品饮。",
  },
  {
    id: "porcelain",
    name: "瓷器",
    category: "绸缎",
    shopType: "silk-shop",
    rarity: "rare",
    basePrice: 320,
    minPrice: 220,
    maxPrice: 620,
    unit: "套",
    originTags: ["江南", "商业"],
    demandTags: ["富城", "大城"],
    description: "窑场烧制的细白瓷，远近都有买主。",
  },
  {
    id: "spice",
    name: "香料",
    category: "绸缎",
    shopType: "silk-shop",
    rarity: "rare",
    basePrice: 390,
    minPrice: 260,
    maxPrice: 720,
    unit: "盒",
    originTags: ["海贸", "番货"],
    demandTags: ["富城", "商业"],
    description: "随海贸而来的香料，价高但利润也厚。",
  },
  {
    id: "suzhou-embroidery",
    name: "苏绣",
    category: "绸缎",
    shopType: "silk-shop",
    rarity: "rare",
    basePrice: 520,
    minPrice: 340,
    maxPrice: 960,
    unit: "幅",
    originTags: ["江南"],
    demandTags: ["富城", "大城"],
    description: "细致华美的刺绣，多为富户与官绅收藏。",
  },
  {
    id: "ironware",
    name: "铁器",
    category: "军械",
    shopType: "smithy",
    rarity: "common",
    basePrice: 190,
    minPrice: 120,
    maxPrice: 320,
    unit: "件",
    originTags: ["矿山", "北地"],
    demandTags: ["军事", "边城"],
    description: "刀具农具皆可归入其列，是军民皆需的货物。",
  },
  {
    id: "gunpowder",
    name: "火药",
    category: "军械",
    shopType: "smithy",
    rarity: "rare",
    basePrice: 460,
    minPrice: 280,
    maxPrice: 860,
    unit: "桶",
    originTags: ["军事", "工坊"],
    demandTags: ["战争", "军事"],
    description: "军中紧要之物，战事一起价格易暴涨。",
  },
  {
    id: "bowstring",
    name: "弓弦",
    category: "军械",
    shopType: "smithy",
    rarity: "uncommon",
    basePrice: 140,
    minPrice: 90,
    maxPrice: 250,
    unit: "副",
    originTags: ["工坊"],
    demandTags: ["军事", "边城"],
    description: "军民都能用到的耗材，边地销量尤佳。",
  },
  {
    id: "armor-plate",
    name: "甲片",
    category: "军械",
    shopType: "smithy",
    rarity: "uncommon",
    basePrice: 250,
    minPrice: 160,
    maxPrice: 430,
    unit: "组",
    originTags: ["工坊", "矿山"],
    demandTags: ["军事", "战争"],
    description: "甲胄修补与打造时不可或缺的材料。",
  },
  {
    id: "spearhead",
    name: "长枪头",
    category: "军械",
    shopType: "smithy",
    rarity: "uncommon",
    basePrice: 200,
    minPrice: 130,
    maxPrice: 340,
    unit: "枚",
    originTags: ["工坊"],
    demandTags: ["军事", "战争"],
    description: "步军常用兵器部件，战时需求总会增加。",
  },
  {
    id: "warhorse",
    name: "战马",
    category: "马市",
    shopType: "horse-market",
    rarity: "rare",
    basePrice: 800,
    minPrice: 500,
    maxPrice: 1500,
    unit: "匹",
    originTags: ["草原"],
    demandTags: ["战争", "军事"],
    description: "北地军马，适合骑战。",
  },
  {
    id: "packhorse",
    name: "驮马",
    category: "马市",
    shopType: "horse-market",
    rarity: "uncommon",
    basePrice: 520,
    minPrice: 320,
    maxPrice: 900,
    unit: "匹",
    originTags: ["草原", "商路"],
    demandTags: ["商业", "边城"],
    description: "耐走耐驮，是长途商队的好帮手。",
  },
  {
    id: "mongol-horse",
    name: "蒙古马",
    category: "马市",
    shopType: "horse-market",
    rarity: "rare",
    basePrice: 760,
    minPrice: 460,
    maxPrice: 1380,
    unit: "匹",
    originTags: ["草原"],
    demandTags: ["战争", "边城"],
    description: "耐力极佳的草原良马，边军尤其看重。",
  },
  {
    id: "antique",
    name: "古董",
    category: "特殊",
    shopType: "general-store",
    rarity: "rare",
    basePrice: 600,
    minPrice: 360,
    maxPrice: 1100,
    unit: "件",
    originTags: ["大城", "旧都"],
    demandTags: ["富城"],
    description: "来路复杂的旧器玩物，识货者愿出高价。",
  },
  {
    id: "secret-letter",
    name: "密信",
    category: "特殊",
    shopType: "general-store",
    rarity: "epic",
    basePrice: 700,
    minPrice: 420,
    maxPrice: 1300,
    unit: "封",
    originTags: ["官场", "商路"],
    demandTags: ["军事", "大城"],
    description: "不可示人的信札，价值常随局势骤变。",
  },
  {
    id: "private-salt",
    name: "私盐",
    category: "特殊",
    shopType: "general-store",
    rarity: "uncommon",
    basePrice: 260,
    minPrice: 160,
    maxPrice: 480,
    unit: "担",
    originTags: ["海贸", "商业"],
    demandTags: ["边城", "灾荒"],
    description: "官禁之物，利润可观但风险不小。",
  },
  {
    id: "foreign-goods",
    name: "番货",
    category: "特殊",
    shopType: "general-store",
    rarity: "rare",
    basePrice: 430,
    minPrice: 260,
    maxPrice: 760,
    unit: "箱",
    originTags: ["海贸", "番货"],
    demandTags: ["商业", "富城"],
    description: "来自海外的稀罕物件，最适合在繁华大城脱手。",
  },
];
