import type {
  SettlementTradeGoodDefinition,
  SettlementTradeGoodId,
} from "../../domain/settlement-trade";

export const settlementTradeGoodsById = {
  silk_textiles: {
    id: "silk_textiles",
    name: "Silk Textiles",
    categoryLabel: "Textiles",
    unit: "bolt",
    basePrice: 180,
    description: "Fine silk bolts aimed at high-status buyers and gift traffic.",
  },
  ramie_cloth: {
    id: "ramie_cloth",
    name: "Ramie Cloth",
    categoryLabel: "Textiles",
    unit: "bolt",
    basePrice: 112,
    description: "Light cloth with steady everyday demand in warmer cities.",
  },
  cotton_cloth: {
    id: "cotton_cloth",
    name: "Cotton Cloth",
    categoryLabel: "Textiles",
    unit: "bolt",
    basePrice: 96,
    description: "Durable cloth that moves well in bulk through inland routes.",
  },
  tea: {
    id: "tea",
    name: "Tea",
    categoryLabel: "Food",
    unit: "crate",
    basePrice: 124,
    description: "Packed tea cargo that travels well and retains value.",
  },
  wine: {
    id: "wine",
    name: "Wine",
    categoryLabel: "Food",
    unit: "jar",
    basePrice: 146,
    description: "Sealed wine favored by taverns, banquets, and gift brokers.",
  },
  ceramics: {
    id: "ceramics",
    name: "Ceramics",
    categoryLabel: "Craft",
    unit: "crate",
    basePrice: 138,
    description: "Kiln-fired wares that reward careful route planning.",
  },
  copperware: {
    id: "copperware",
    name: "Copperware",
    categoryLabel: "Metalware",
    unit: "crate",
    basePrice: 158,
    description: "Worked copper utensils and fittings with artisan demand.",
  },
  ironware: {
    id: "ironware",
    name: "Ironware",
    categoryLabel: "Metalware",
    unit: "crate",
    basePrice: 132,
    description: "Tools and hardware that stay relevant in frontier markets.",
  },
  salt: {
    id: "salt",
    name: "Salt",
    categoryLabel: "Staples",
    unit: "load",
    basePrice: 84,
    description: "Reliable staple cargo with strong margins in interior cities.",
  },
  paper_brush: {
    id: "paper_brush",
    name: "Paper and Brush",
    categoryLabel: "Scholar Goods",
    unit: "bundle",
    basePrice: 128,
    description: "Writing supplies bought by clerks, schools, and officials.",
  },
  bamboo_woodware: {
    id: "bamboo_woodware",
    name: "Bamboo Woodware",
    categoryLabel: "Craft",
    unit: "crate",
    basePrice: 98,
    description: "Light household wares that travel efficiently on mixed routes.",
  },
  woven_goods: {
    id: "woven_goods",
    name: "Woven Goods",
    categoryLabel: "Craft",
    unit: "crate",
    basePrice: 118,
    description: "Durable woven goods suited to wagon and caravan trade.",
  },
  lacquer_oil: {
    id: "lacquer_oil",
    name: "Lacquer and Oil",
    categoryLabel: "Craft",
    unit: "crate",
    basePrice: 164,
    description: "Workshop supplies that spike where finishing trades are active.",
  },
  stone_goods: {
    id: "stone_goods",
    name: "Stone Goods",
    categoryLabel: "Industrial",
    unit: "crate",
    basePrice: 104,
    description: "Worked stone and mineral cargo best moved in planned lots.",
  },
  hides: {
    id: "hides",
    name: "Hides",
    categoryLabel: "Livestock",
    unit: "bundle",
    basePrice: 108,
    description: "Hide bundles and leather stock favored by military buyers.",
  },
} as const satisfies Record<SettlementTradeGoodId, SettlementTradeGoodDefinition>;
