import type {
  SettlementTradeGoodDefinition,
  SettlementTradeGoodId,
} from "../../domain/settlement-trade";

export const settlementTradeGoodsById = {
  silk_textiles: {
    id: "silk_textiles",
    name: "丝绸",
    categoryLabel: "织品",
    unit: "匹",
    basePrice: 180,
    description: "上等丝绸，最适合卖给富户、豪门与讲究体面的买家。",
  },
  ramie_cloth: {
    id: "ramie_cloth",
    name: "麻布",
    categoryLabel: "织品",
    unit: "匹",
    basePrice: 112,
    description: "轻便耐穿，南方暖热地带的日常用布向来走得稳。",
  },
  cotton_cloth: {
    id: "cotton_cloth",
    name: "棉布",
    categoryLabel: "织品",
    unit: "匹",
    basePrice: 96,
    description: "耐用实惠，最适合走内陆大宗商路。",
  },
  tea: {
    id: "tea",
    name: "茶叶",
    categoryLabel: "食货",
    unit: "箱",
    basePrice: 124,
    description: "耐运耐放，沿水路与长途商道都能保住身价。",
  },
  wine: {
    id: "wine",
    name: "酒",
    categoryLabel: "食货",
    unit: "坛",
    basePrice: 146,
    description: "酒楼、宴席与送礼场面都少不了封坛好酒。",
  },
  ceramics: {
    id: "ceramics",
    name: "瓷器",
    categoryLabel: "器物",
    unit: "箱",
    basePrice: 138,
    description: "窑货怕颠簸，走对商路就能卖出好价。",
  },
  copperware: {
    id: "copperware",
    name: "铜器",
    categoryLabel: "金铁",
    unit: "箱",
    basePrice: 158,
    description: "铜制器皿与配件最受工匠行和殷实人家欢迎。",
  },
  ironware: {
    id: "ironware",
    name: "铁器",
    categoryLabel: "金铁",
    unit: "箱",
    basePrice: 132,
    description: "工具与五金在边城和修筑地向来不愁出手。",
  },
  salt: {
    id: "salt",
    name: "盐",
    categoryLabel: "日用",
    unit: "担",
    basePrice: 84,
    description: "最稳妥的日用货，越往内陆越容易抬价。",
  },
  paper_brush: {
    id: "paper_brush",
    name: "纸笔",
    categoryLabel: "文房",
    unit: "捆",
    basePrice: 128,
    description: "衙门、书吏、学塾都离不开纸笔文具。",
  },
  bamboo_woodware: {
    id: "bamboo_woodware",
    name: "竹木器",
    categoryLabel: "器物",
    unit: "箱",
    basePrice: 98,
    description: "轻巧好装，最适合走水陆混合商道。",
  },
  woven_goods: {
    id: "woven_goods",
    name: "编织货",
    categoryLabel: "器物",
    unit: "箱",
    basePrice: 118,
    description: "结实耐用，适合车队与商帮长途贩运。",
  },
  lacquer_oil: {
    id: "lacquer_oil",
    name: "漆油",
    categoryLabel: "器物",
    unit: "箱",
    basePrice: 164,
    description: "做漆作坊一旺，漆油就会立刻涨价。",
  },
  stone_goods: {
    id: "stone_goods",
    name: "石料器货",
    categoryLabel: "工料",
    unit: "箱",
    basePrice: 104,
    description: "石作与矿料最适合成批整车地规划出货。",
  },
  hides: {
    id: "hides",
    name: "皮货",
    categoryLabel: "皮革",
    unit: "捆",
    basePrice: 108,
    description: "军需、马队和皮作铺子都爱收这类皮货。",
  },
} as const satisfies Record<SettlementTradeGoodId, SettlementTradeGoodDefinition>;
