import type {
  CardDefinition,
  CharacterDefinition,
  CityEntryDefinition,
  CityDefinition,
  CityNpcPoolDefinition,
  HouseDefinition,
  MapDefinition,
  ValuableItemDefinition,
} from "../domain";
import { zhuYuanzhangEarlyCharacters } from "./zhu-yuanzhang-early-characters";

export const prototypeMap: MapDefinition = {
  id: "map.prototype_frontier",
  name: "边境地图",
  backgroundId: "bg.map.prototype_frontier",
  nodes: [{ cityId: "city.kulan", x: 2, y: 2 }],
};

export const prototypeCity: CityDefinition = {
  id: "city.kulan",
  name: "濠州",
  regionId: "region.frontier",
  mapNodeId: "settlement.fenyang_province",
  houseIds: [
    "house.kulan.leader_residence",
    "home_001",
    "house.kulan.keep",
    "house.kulan.tea_house",
    "house.kulan.market",
    "house.kulan.grain_shop",
    "house.kulan.inn",
  ],
  neighbourCityIds: [],
  travelCost: 1,
  tags: ["castle-town", "market", "commercial", "jiangnan", "large-city"],
  prosperity: 90,
  danger: 20,
  specialDemand: ["silk", "tea", "luxury"],
};

export const prototypeCities: CityDefinition[] = [prototypeCity];

export const prototypeHouses: HouseDefinition[] = [
  {
    id: "house.kulan.leader_residence",
    cityId: "city.kulan",
    name: "将领府邸",
    type: "residence",
    moduleId: "leader-residence",
    characterIds: [],
    defaultCharacterId: null,
    backAction: {
      label: "返回濠州",
      targetView: "city",
    },
  },
  {
    id: "home_001",
    cityId: "city.kulan",
    name: "自宅",
    type: "residence",
    moduleId: "home-house",
    characterIds: [],
    defaultCharacterId: null,
    backAction: {
      label: "返回濠州",
      targetView: "city",
    },
  },
  {
    id: "house.kulan.keep",
    cityId: "city.kulan",
    name: "帅府",
    type: "castle",
    moduleId: "keep-house",
    characterIds: [
      "char.kulan_lord",
      "char.kulan_xu_da",
      "char.kulan_tang_he",
      "char.kulan_chang_yuchun",
      "char.kulan_guard",
    ],
    defaultCharacterId: "char.kulan_lord",
    backAction: {
      label: "返回濠州",
      targetView: "city",
    },
  },
  {
    id: "house.kulan.tea_house",
    cityId: "city.kulan",
    name: "茶馆",
    type: "tea-house",
    characterIds: ["char.kulan_tea_boss"],
    defaultCharacterId: "char.kulan_tea_boss",
    activityLocationId: "tea-house",
    moduleId: "tea-house",
    backAction: {
      label: "返回濠州",
      targetView: "city",
    },
  },
  {
    id: "house.kulan.market",
    cityId: "city.kulan",
    name: "货栈",
    type: "merchant",
    characterIds: ["char.kulan_merchant"],
    defaultCharacterId: "char.kulan_merchant",
    activityLocationId: "market",
    moduleId: "market-house",
    backAction: {
      label: "返回濠州",
      targetView: "city",
    },
  },
  {
    id: "house.kulan.grain_shop",
    cityId: "city.kulan",
    name: "粮铺",
    type: "merchant",
    moduleId: "grain-shop",
    characterIds: ["char.kulan_grain_shopkeeper"],
    defaultCharacterId: "char.kulan_grain_shopkeeper",
    backAction: {
      label: "返回濠州",
      targetView: "city",
    },
  },
  {
    id: "house.kulan.inn",
    cityId: "city.kulan",
    name: "客栈",
    type: "inn",
    moduleId: "tavern",
    characterIds: ["char.kulan_innkeeper"],
    defaultCharacterId: "char.kulan_innkeeper",
    activityLocationId: "tavern",
    backAction: {
      label: "返回濠州",
      targetView: "city",
    },
  },
];

export const prototypeCityEntries: CityEntryDefinition[] = [
  {
    id: "city-entry.kulan.leader-residence",
    cityId: "city.kulan",
    name: "将领府邸",
    directoryType: "leader-residence",
    targetHouseId: "house.kulan.leader_residence",
    artworkId: "leader-residence",
  },
];

export const prototypeCharacters: CharacterDefinition[] = [
  {
    id: "char.player",
    name: "朱元璋",
    birthYear: 1535,
    deathYear: null,
    age: 32,
    clanId: "clan.guo",
    title: "亲兵",
    occupation: "军中跑腿",
    cityId: "city.kulan",
    houseId: "home_001",
    portraitId: "portrait.player",
    portraitVariants: [
      {
        id: "normal",
        label: "通常",
        portraitId: "portrait.player.normal",
      },
      {
        id: "smile",
        label: "微笑",
        portraitId: "portrait.player.smile",
      },
    ],
    portraitVariantId: "normal",
    stats: {
      leadership: 60,
      martial: 58,
      intelligence: 55,
      politics: 42,
      charm: 51,
      fame: 8,
      gold: 120,
    },
    stamina: 100,
    biography: "郭子兴帐下的新近亲兵，资历尚浅，先从跑腿与粮道杂务做起。",
    availableFunctions: [],
    skills: {
      ashigaru: 2,
      horse: 3,
      teppo: 1,
      navy: 0,
      archery: 1,
      martial: 2,
      military: 2,
      ninjutsu: 0,
      construction: 0,
      development: 1,
      mining: 0,
      arithmetic: 1,
      etiquette: 2,
      rhetoric: 1,
      tea: 1,
      medicine: 0,
    },
  },
  {
    id: "char.kulan_lord",
    name: "郭子兴",
    birthYear: 1528,
    deathYear: null,
    age: 39,
    clanId: "clan.guo",
    title: "主帅",
    occupation: "红巾军首领",
    cityId: "city.kulan",
    houseId: "house.kulan.keep",
    portraitId: "portrait.kulan_lord",
    stats: {
      leadership: 74,
      martial: 63,
      intelligence: 70,
      politics: 68,
      charm: 61,
      fame: 38,
      gold: 600,
    },
    stamina: 88,
    biography: "郭子兴坐镇濠州，掌军政、定方略，也亲自主持每一轮评定。",
    availableFunctions: [],
    skills: {
      ashigaru: 3,
      horse: 4,
      teppo: 2,
      navy: 0,
      archery: 2,
      martial: 4,
      military: 3,
      ninjutsu: 0,
      construction: 2,
      development: 2,
      mining: 0,
      arithmetic: 2,
      etiquette: 3,
      rhetoric: 2,
      tea: 2,
      medicine: 1,
    },
  },
  {
    id: "char.kulan_guard",
    name: "孙德崖",
    birthYear: 1542,
    deathYear: null,
    age: 25,
    clanId: "clan.guo",
    title: "卫士",
    occupation: "步卒",
    cityId: "city.kulan",
    houseId: "house.kulan.keep",
    portraitId: "portrait.kulan_guard",
    stats: {
      leadership: 40,
      martial: 49,
      intelligence: 29,
      politics: 18,
      charm: 24,
      fame: 4,
      gold: 20,
    },
    stamina: 76,
    biography: "常在帅府值守，也负责传递军令。",
    availableFunctions: [],
    skills: {
      ashigaru: 4,
      horse: 1,
      teppo: 1,
      navy: 0,
      archery: 0,
      martial: 2,
      military: 1,
      ninjutsu: 0,
      construction: 0,
      development: 0,
      mining: 0,
      arithmetic: 0,
      etiquette: 1,
      rhetoric: 0,
      tea: 0,
      medicine: 0,
    },
  },
  {
    id: "char.kulan_xu_da",
    name: "徐达",
    birthYear: 1531,
    deathYear: null,
    age: 36,
    clanId: "clan.guo",
    title: "前锋大将",
    occupation: "武将",
    cityId: "city.kulan",
    houseId: "house.kulan.keep",
    portraitId: "portrait.kulan_xu_da",
    affiliationLabel: "濠州军中",
    stats: {
      leadership: 81,
      martial: 76,
      intelligence: 62,
      politics: 48,
      charm: 54,
      fame: 30,
      gold: 180,
    },
    stamina: 92,
    biography: "作战沉稳，军中多以徐达为前锋。",
    availableFunctions: [],
    skills: {
      ashigaru: 4,
      horse: 4,
      teppo: 1,
      navy: 0,
      archery: 2,
      martial: 4,
      military: 4,
      ninjutsu: 0,
      construction: 1,
      development: 1,
      mining: 0,
      arithmetic: 1,
      etiquette: 1,
      rhetoric: 1,
      tea: 0,
      medicine: 0,
    },
  },
  {
    id: "char.kulan_tang_he",
    name: "汤和",
    birthYear: 1530,
    deathYear: null,
    age: 37,
    clanId: "clan.guo",
    title: "宿将",
    occupation: "武将",
    cityId: "city.kulan",
    houseId: "house.kulan.keep",
    portraitId: "portrait.kulan_tang_he",
    stats: {
      leadership: 75,
      martial: 67,
      intelligence: 58,
      politics: 44,
      charm: 52,
      fame: 26,
      gold: 150,
    },
    stamina: 86,
    biography: "资历深，善于整顿营伍与催督军粮。",
    availableFunctions: [],
    skills: {
      ashigaru: 4,
      horse: 3,
      teppo: 1,
      navy: 0,
      archery: 1,
      martial: 3,
      military: 4,
      ninjutsu: 0,
      construction: 1,
      development: 1,
      mining: 0,
      arithmetic: 1,
      etiquette: 1,
      rhetoric: 1,
      tea: 0,
      medicine: 0,
    },
  },
  {
    id: "char.kulan_chang_yuchun",
    name: "常遇春",
    birthYear: 1534,
    deathYear: null,
    age: 33,
    clanId: "clan.guo",
    title: "骁将",
    occupation: "武将",
    cityId: "city.kulan",
    houseId: "house.kulan.keep",
    portraitId: "portrait.kulan_chang_yuchun",
    stats: {
      leadership: 73,
      martial: 79,
      intelligence: 46,
      politics: 28,
      charm: 47,
      fame: 22,
      gold: 90,
    },
    stamina: 94,
    biography: "性急勇悍，最擅长冲阵夺旗。",
    availableFunctions: [],
    skills: {
      ashigaru: 4,
      horse: 4,
      teppo: 0,
      navy: 0,
      archery: 1,
      martial: 4,
      military: 3,
      ninjutsu: 0,
      construction: 0,
      development: 0,
      mining: 0,
      arithmetic: 0,
      etiquette: 0,
      rhetoric: 0,
      tea: 0,
      medicine: 0,
    },
  },
  {
    id: "char.kulan_liu_bowen",
    name: "刘伯温",
    birthYear: 1536,
    deathYear: null,
    age: 31,
    clanId: "clan.guo",
    title: "乡贤",
    occupation: "谋士",
    affiliationLabel: "濠州士人",
    cityId: "city.kulan",
    houseId: "house.kulan.leader_residence",
    portraitId: "portrait.kulan_liu_bowen",
    stats: {
      leadership: 52,
      martial: 20,
      intelligence: 86,
      politics: 81,
      charm: 72,
      fame: 28,
      gold: 90,
    },
    stamina: 74,
    biography: "通经史、善权谋，在濠州颇有声望，常为群雄筹画进退。",
    isHistoricalFigure: true,
    leaderResidenceEligible: true,
    leaderResidenceStatus: "available",
    availableFunctions: [],
    skills: {
      ashigaru: 0,
      horse: 0,
      teppo: 0,
      navy: 0,
      archery: 0,
      martial: 1,
      military: 4,
      ninjutsu: 0,
      construction: 2,
      development: 3,
      mining: 0,
      arithmetic: 3,
      etiquette: 3,
      rhetoric: 4,
      tea: 2,
      medicine: 1,
    },
    teachableSkillKeys: ["military", "arithmetic", "rhetoric", "etiquette"],
  },
  {
    id: "char.kulan_li_shanchang",
    name: "李善长",
    birthYear: 1526,
    deathYear: null,
    age: 41,
    clanId: "clan.guo",
    title: "乡贤",
    occupation: "幕僚",
    affiliationLabel: "濠州士人",
    cityId: "city.kulan",
    houseId: "house.kulan.leader_residence",
    portraitId: "portrait.kulan_li_shanchang",
    stats: {
      leadership: 48,
      martial: 18,
      intelligence: 82,
      politics: 84,
      charm: 69,
      fame: 25,
      gold: 110,
    },
    stamina: 70,
    biography: "精于文案与政务，善衡轻重，是城中名望颇高的乡贤人物。",
    isHistoricalFigure: true,
    leaderResidenceEligible: true,
    leaderResidenceStatus: "available",
    availableFunctions: [],
    skills: {
      ashigaru: 0,
      horse: 0,
      teppo: 0,
      navy: 0,
      archery: 0,
      martial: 0,
      military: 3,
      ninjutsu: 0,
      construction: 1,
      development: 4,
      mining: 0,
      arithmetic: 3,
      etiquette: 4,
      rhetoric: 3,
      tea: 2,
      medicine: 0,
    },
    teachableSkillKeys: ["development", "etiquette", "arithmetic"],
  },
  {
    id: "char.kulan_tea_boss",
    name: "柳四",
    birthYear: 1534,
    deathYear: null,
    age: 33,
    title: "茶馆老板",
    occupation: "茶馆老板",
    cityId: "city.kulan",
    houseId: "house.kulan.tea_house",
    portraitId: "portrait.kulan_tea_boss",
    stats: {
      leadership: 28,
      martial: 19,
      intelligence: 63,
      politics: 54,
      charm: 71,
      fame: 14,
      gold: 180,
    },
    stamina: 78,
    biography: "柳四经营着濠州的茶馆，擅长把零散传闻拼成线索。",
    availableFunctions: [],
    skills: {
      ashigaru: 0,
      horse: 0,
      teppo: 0,
      navy: 0,
      archery: 0,
      martial: 0,
      military: 0,
      ninjutsu: 0,
      construction: 0,
      development: 1,
      mining: 0,
      arithmetic: 2,
      etiquette: 3,
      rhetoric: 4,
      tea: 3,
      medicine: 0,
    },
  },
  {
    id: "char.kulan_grain_shopkeeper",
    name: "陈掌柜",
    birthYear: 1531,
    deathYear: null,
    age: 36,
    title: "掌柜",
    occupation: "商人",
    cityId: "city.kulan",
    houseId: "house.kulan.grain_shop",
    portraitId: "portrait.kulan_grain_shopkeeper",
    stats: {
      leadership: 30,
      martial: 18,
      intelligence: 68,
      politics: 62,
      charm: 55,
      fame: 10,
      gold: 500,
    },
    stamina: 70,
    biography: "陈记粮铺掌柜，熟悉南北粮路与市价起伏。",
    availableFunctions: [],
    skills: {
      ashigaru: 0,
      horse: 0,
      teppo: 0,
      navy: 0,
      archery: 0,
      martial: 0,
      military: 0,
      ninjutsu: 0,
      construction: 0,
      development: 2,
      mining: 0,
      arithmetic: 4,
      etiquette: 2,
      rhetoric: 2,
      tea: 1,
      medicine: 0,
    },
  },
  {
    id: "char.kulan_merchant",
    name: "钱掌柜",
    birthYear: 1530,
    deathYear: null,
    age: 37,
    title: "货栈老板",
    occupation: "商人",
    cityId: "city.kulan",
    houseId: "house.kulan.market",
    portraitId: "portrait.kulan_merchant",
    stats: {
      leadership: 32,
      martial: 21,
      intelligence: 71,
      politics: 66,
      charm: 58,
      fame: 12,
      gold: 900,
    },
    stamina: 72,
    biography: "濠州货栈的掌柜，最擅长盘算商路差价与各城货价起落。",
    availableFunctions: [],
    skills: {
      ashigaru: 1,
      horse: 1,
      teppo: 0,
      navy: 0,
      archery: 0,
      martial: 0,
      military: 1,
      ninjutsu: 0,
      construction: 0,
      development: 3,
      mining: 0,
      arithmetic: 4,
      etiquette: 2,
      rhetoric: 3,
      tea: 2,
      medicine: 0,
    },
  },
  {
    id: "char.kulan_innkeeper",
    name: "客栈老板娘",
    birthYear: 1533,
    deathYear: null,
    age: 34,
    title: "掌柜",
    occupation: "旅宿主人",
    cityId: "city.kulan",
    houseId: "house.kulan.inn",
    portraitId: "portrait.kulan_innkeeper",
    stats: {
      leadership: 28,
      martial: 19,
      intelligence: 62,
      politics: 57,
      charm: 74,
      fame: 16,
      gold: 260,
    },
    stamina: 80,
    biography: "熟悉来往旅客与城内传闻的客栈掌柜。",
    availableFunctions: [],
    skills: {
      ashigaru: 0,
      horse: 0,
      teppo: 0,
      navy: 0,
      archery: 0,
      martial: 0,
      military: 0,
      ninjutsu: 0,
      construction: 0,
      development: 1,
      mining: 0,
      arithmetic: 2,
      etiquette: 3,
      rhetoric: 3,
      tea: 2,
      medicine: 1,
    },
  },
];

const leaderResidenceCharacterOverrides: Record<
  string,
  Partial<CharacterDefinition>
> = {
  "char.kulan_xu_da": {
    name: "徐达",
    title: "前锋大将",
    occupation: "武将",
    affiliationLabel: "濠州军中",
    biography: "作战沉稳，军中多以徐达为前锋，善于统兵推进。",
    isHistoricalFigure: true,
    leaderResidenceEligible: true,
    leaderResidenceStatus: "available",
    teachableSkillKeys: ["military", "horse", "martial"],
  },
  "char.kulan_tang_he": {
    name: "汤和",
    title: "宿将",
    occupation: "武将",
    affiliationLabel: "濠州军中",
    biography: "资历深厚，善于整顿营伍与督军，是军中老成持重之将。",
    isHistoricalFigure: true,
    leaderResidenceEligible: true,
    leaderResidenceStatus: "available",
    teachableSkillKeys: ["military", "construction", "etiquette"],
  },
  "char.kulan_chang_yuchun": {
    name: "常遇春",
    title: "骁将",
    occupation: "武将",
    affiliationLabel: "濠州军中",
    biography: "性急勇悍，最擅长冲阵夺旗，是军中锋锐人物。",
    isHistoricalFigure: true,
    leaderResidenceEligible: true,
    leaderResidenceStatus: "available",
    teachableSkillKeys: ["martial", "horse", "ashigaru"],
  },
  "char.kulan_liu_bowen": {
    name: "刘伯温",
    title: "乡贤",
    occupation: "谋士",
    affiliationLabel: "濠州士人",
    biography: "通经史、善权谋，在濠州颇有声望，常为群雄筹画进退。",
  },
  "char.kulan_li_shanchang": {
    name: "李善长",
    title: "乡贤",
    occupation: "幕僚",
    affiliationLabel: "濠州士人",
    biography: "精于文案与政务，善权轻重，是城中名望颇高的乡贤人物。",
  },
};

for (const characterDefinition of prototypeCharacters) {
  const override = leaderResidenceCharacterOverrides[characterDefinition.id];
  if (override != null) {
    Object.assign(characterDefinition, override);
  }
}

export const prototypeHistoricalCharacterIdByCharacterId: Record<string, string> = {
  "char.kulan_lord": "zyz.character.guo_zixing",
  "char.kulan_tang_he": "zyz.character.tang_he",
  "char.kulan_xu_da": "zyz.character.xu_da",
  "char.kulan_chang_yuchun": "zyz.character.chang_yuchun",
  "char.kulan_li_shanchang": "zyz.character.li_shanchang",
  "char.kulan_liu_bowen": "zyz.character.liu_ji",
};

export const prototypeLeaderResidenceHistoricalCharacters =
  zhuYuanzhangEarlyCharacters;

export const prototypeCityNpcPools: CityNpcPoolDefinition[] = [
  {
    cityId: "city.kulan",
    residents: [
      {
        id: "city-npc.kulan.merchant_zhou",
        cityId: "city.kulan",
        name: "周掌柜",
        title: "盐商",
        personality: "精明",
        specialty: "交易",
        favorability: 0,
        activityWeight: {
          "tea-house": 20,
          tavern: 10,
          market: 60,
          street: 10,
        },
        dialoguePool: ["盐路一断，市价三日就要翻。"],
        intelPool: ["北边商路这几日有运盐队入城。"],
      },
      {
        id: "city-npc.kulan.scholar_he",
        cityId: "city.kulan",
        name: "何秀才",
        title: "落榜书生",
        personality: "傲气",
        specialty: "辩论",
        favorability: 0,
        activityWeight: {
          "tea-house": 50,
          tavern: 10,
          market: 10,
          street: 30,
        },
        dialoguePool: ["世人只问功名，不问文章。"],
        intelPool: ["帅府近日似乎在招募能写文书的人。"],
      },
      {
        id: "city-npc.kulan.wanderer_wu",
        cityId: "city.kulan",
        name: "老吴",
        title: "货郎",
        personality: "豪爽",
        specialty: "见闻",
        favorability: 0,
        activityWeight: {
          "tea-house": 25,
          tavern: 25,
          market: 30,
          street: 20,
        },
        dialoguePool: ["走南闯北的人，最重要的是眼睛和耳朵。"],
        intelPool: ["集市上有人在悄悄收购铁料。"],
      },
      {
        id: "city-npc.kulan.guard_lin",
        cityId: "city.kulan",
        name: "林镖头",
        title: "镖师",
        personality: "警惕",
        specialty: "江湖",
        favorability: 0,
        activityWeight: {
          "tea-house": 15,
          tavern: 35,
          market: 20,
          street: 30,
        },
        dialoguePool: ["喝酒可以，别在我背后站太久。"],
        intelPool: ["最近有人在打听出城商队的时辰。"],
      },
    ],
  },
];

export const prototypeCityPortraits: Record<string, string> = {
  "city.kulan": "濠州",
};

export const prototypeCards: CardDefinition[] = [
  {
    id: "card.one_strike",
    name: "一齐攻击",
    category: "battle",
    skillDescription: "让部队集中攻击目标。",
    battlefieldDisplay: "战场全体突击",
    ammoCostText: "使用兵粮：没有限制",
    cardImageId: "card-image.one_strike",
    logicNotes: "用于强制推进战斗回合的核心合战卡。",
  },
  {
    id: "card.secret_step",
    name: "强袭",
    category: "secret-technique",
    skillDescription: "以快速行动突破防线。",
    battlefieldDisplay: "战场快速突入",
    ammoCostText: "使用兵粮：没有限制",
    cardImageId: "card-image.secret_step",
    logicNotes: "可作为忍术或特殊战术动作的基础。",
  },
  {
    id: "card.fire_attack",
    name: "火攻",
    category: "battle",
    skillDescription: "借火势破坏敌阵。",
    battlefieldDisplay: "战场火攻范围",
    ammoCostText: "使用兵粮：需要火具或火计资源",
    cardImageId: "card-image.fire_attack",
    logicNotes: "后续可绑定天气、地形和火攻成功率。",
  },
];

export const prototypeValuables: ValuableItemDefinition[] = [
  {
    id: "item.sword.ogasa",
    name: "胁差",
    category: "weapon",
    price: 1,
    ownedCount: 1,
    kindText: "刀剑",
    itemImageId: "item-image.sword.ogasa",
    description: "无名匠所制的腰刀。",
  },
  {
    id: "item.armor.tetsu",
    name: "铁札足",
    category: "armor",
    price: 1,
    ownedCount: 1,
    kindText: "铠甲",
    itemImageId: "item-image.armor.tetsu",
    description: "基础护具，适合近身防护。",
  },
];
