import type {
  CardDefinition,
  CharacterDefinition,
  CityDefinition,
  CityNpcPoolDefinition,
  HouseDefinition,
  MapDefinition,
  ValuableItemDefinition,
} from "../domain";

export const prototypeMap: MapDefinition = {
  id: "map.prototype_frontier",
  name: "边境地图",
  backgroundId: "bg.map.prototype_frontier",
  nodes: [{ cityId: "city.kulan", x: 2, y: 2 }],
};

export const prototypeCity: CityDefinition = {
  id: "city.kulan",
  name: "顺天府",
  regionId: "region.frontier",
  mapNodeId: "settlement.yingtian_province",
  houseIds: [
    "house.kulan.keep",
    "house.kulan.tea_house",
    "house.kulan.market",
    "house.kulan.grain_shop",
    "house.kulan.inn",
  ],
  neighbourCityIds: [],
  travelCost: 1,
  tags: ["castle-town", "market"],
};

export const prototypeHouses: HouseDefinition[] = [
  {
    id: "house.kulan.keep",
    cityId: "city.kulan",
    name: "城主府",
    type: "castle",
    characterIds: ["char.kulan_lord", "char.kulan_guard"],
    defaultCharacterId: "char.kulan_lord",
    backAction: {
      label: "返回库兰城",
      targetView: "city",
    },
  },
  {
    id: "house.kulan.tea_house",
    cityId: "city.kulan",
    name: "茶馆",
    type: "tea-house",
    characterIds: ["char.kulan_tea_boss"],
    defaultCharacterId: "char.kulan_tea_boss",
    activityLocationId: "tea-house",
    moduleId: "tea-house",
    backAction: {
      label: "返回库兰城",
      targetView: "city",
    },
  },
  {
    id: "house.kulan.market",
    cityId: "city.kulan",
    name: "商馆",
    type: "merchant",
    characterIds: ["char.kulan_merchant"],
    defaultCharacterId: "char.kulan_merchant",
    activityLocationId: "market",
    backAction: {
      label: "返回库兰城",
      targetView: "city",
    },
  },
  {
    id: "house.kulan.grain_shop",
    cityId: "city.kulan",
    name: "粮铺",
    type: "merchant",
    moduleId: "grain-shop",
    characterIds: ["char.kulan_grain_shopkeeper"],
    defaultCharacterId: "char.kulan_grain_shopkeeper",
    backAction: {
      label: "返回库兰城",
      targetView: "city",
    },
  },
  {
    id: "house.kulan.inn",
    cityId: "city.kulan",
    name: "宿场",
    type: "inn",
    moduleId: "tavern",
    characterIds: ["char.kulan_innkeeper"],
    defaultCharacterId: "char.kulan_innkeeper",
    activityLocationId: "tavern",
    backAction: {
      label: "返回库兰城",
      targetView: "city",
    },
  },
];

export const prototypeCharacters: CharacterDefinition[] = [
  {
    id: "char.player",
    name: "旅人",
    birthYear: 1535,
    deathYear: null,
    age: 32,
    title: "无主浪人",
    occupation: "浪人",
    cityId: "city.kulan",
    portraitId: "portrait.player",
    portraitVariants: [
      {
        id: "normal",
        label: "通常",
        portraitId: "portrait.player.normal",
      },
      {
        id: "smile",
        label: "微笑",
        portraitId: "portrait.player.smile",
      },
    ],
    portraitVariantId: "normal",
    stats: {
      leadership: 60,
      martial: 58,
      intelligence: 55,
      politics: 42,
      charm: 51,
      fame: 8,
      gold: 120,
    },
    stamina: 100,
    biography: "边境上游走的浪人，暂时没有固定主家。",
    availableFunctions: [],
    skills: {
      ashigaru: 2,
      horse: 3,
      teppo: 1,
      navy: 0,
      archery: 1,
      martial: 2,
      military: 2,
      ninjutsu: 0,
      construction: 0,
      development: 1,
      mining: 0,
      arithmetic: 1,
      etiquette: 2,
      rhetoric: 1,
      tea: 1,
      medicine: 0,
    },
  },
  {
    id: "char.kulan_lord",
    name: "库兰城主",
    birthYear: 1528,
    deathYear: null,
    age: 39,
    title: "镇守",
    occupation: "武士",
    cityId: "city.kulan",
    houseId: "house.kulan.keep",
    portraitId: "portrait.kulan_lord",
    stats: {
      leadership: 74,
      martial: 63,
      intelligence: 70,
      politics: 68,
      charm: 61,
      fame: 38,
      gold: 600,
    },
    stamina: 88,
    biography: "库兰城的实际统治者，负责城内秩序和主家任务下达。",
    availableFunctions: [],
    skills: {
      ashigaru: 3,
      horse: 4,
      teppo: 2,
      navy: 0,
      archery: 2,
      martial: 4,
      military: 3,
      ninjutsu: 0,
      construction: 2,
      development: 2,
      mining: 0,
      arithmetic: 2,
      etiquette: 3,
      rhetoric: 2,
      tea: 2,
      medicine: 1,
    },
  },
  {
    id: "char.kulan_guard",
    name: "城门番",
    birthYear: 1542,
    deathYear: null,
    age: 25,
    title: "守卫",
    occupation: "足轻",
    cityId: "city.kulan",
    houseId: "house.kulan.keep",
    portraitId: "portrait.kulan_guard",
    stats: {
      leadership: 40,
      martial: 49,
      intelligence: 29,
      politics: 18,
      charm: 24,
      fame: 4,
      gold: 20,
    },
    stamina: 76,
    biography: "负责库兰城城门巡查的普通守卫。",
    availableFunctions: [],
    skills: {
      ashigaru: 4,
      horse: 1,
      teppo: 1,
      navy: 0,
      archery: 0,
      martial: 2,
      military: 1,
      ninjutsu: 0,
      construction: 0,
      development: 0,
      mining: 0,
      arithmetic: 0,
      etiquette: 1,
      rhetoric: 0,
      tea: 0,
      medicine: 0,
    },
  },
  {
    id: "char.kulan_tea_boss",
    name: "柳四",
    birthYear: 1534,
    deathYear: null,
    age: 33,
    title: "茶馆老板",
    occupation: "茶馆老板",
    cityId: "city.kulan",
    houseId: "house.kulan.tea_house",
    portraitId: "portrait.kulan_tea_boss",
    stats: {
      leadership: 28,
      martial: 19,
      intelligence: 63,
      politics: 54,
      charm: 71,
      fame: 14,
      gold: 180,
    },
    stamina: 78,
    biography: "柳四经营着库兰城的茶馆，表面圆滑，实则最擅长把零散传闻拼成线索。",
    availableFunctions: [],
    skills: {
      ashigaru: 0,
      horse: 0,
      teppo: 0,
      navy: 0,
      archery: 0,
      martial: 0,
      military: 0,
      ninjutsu: 0,
      construction: 0,
      development: 1,
      mining: 0,
      arithmetic: 2,
      etiquette: 3,
      rhetoric: 4,
      tea: 3,
      medicine: 0,
    },
  },
  {
    id: "char.kulan_grain_shopkeeper",
    name: "掌柜",
    birthYear: 1531,
    deathYear: null,
    age: 36,
    title: "掌柜",
    occupation: "商人",
    cityId: "city.kulan",
    houseId: "house.kulan.grain_shop",
    portraitId: "portrait.kulan_grain_shopkeeper",
    stats: {
      leadership: 30,
      martial: 18,
      intelligence: 68,
      politics: 62,
      charm: 55,
      fame: 10,
      gold: 500,
    },
    stamina: 70,
    biography: "陈记粮铺掌柜，熟稔南北粮路与市价起伏。",
    availableFunctions: [],
    skills: {
      ashigaru: 0,
      horse: 0,
      teppo: 0,
      navy: 0,
      archery: 0,
      martial: 0,
      military: 0,
      ninjutsu: 0,
      construction: 0,
      development: 2,
      mining: 0,
      arithmetic: 4,
      etiquette: 2,
      rhetoric: 2,
      tea: 1,
      medicine: 0,
    },
  },
  {
    id: "char.kulan_merchant",
    name: "行商头目",
    birthYear: 1530,
    deathYear: null,
    age: 37,
    title: "商人",
    occupation: "商人",
    cityId: "city.kulan",
    houseId: "house.kulan.market",
    portraitId: "portrait.kulan_merchant",
    stats: {
      leadership: 32,
      martial: 21,
      intelligence: 71,
      politics: 66,
      charm: 58,
      fame: 12,
      gold: 900,
    },
    stamina: 72,
    biography: "往来各地的行商头目，对库兰城物资流通十分熟悉。",
    availableFunctions: [],
    skills: {
      ashigaru: 1,
      horse: 1,
      teppo: 0,
      navy: 0,
      archery: 0,
      martial: 0,
      military: 1,
      ninjutsu: 0,
      construction: 0,
      development: 3,
      mining: 0,
      arithmetic: 4,
      etiquette: 2,
      rhetoric: 3,
      tea: 2,
      medicine: 0,
    },
  },
  {
    id: "char.kulan_innkeeper",
    name: "宿场女将",
    birthYear: 1533,
    deathYear: null,
    age: 34,
    title: "掌柜",
    occupation: "旅宿业",
    cityId: "city.kulan",
    houseId: "house.kulan.inn",
    portraitId: "portrait.kulan_innkeeper",
    stats: {
      leadership: 28,
      martial: 19,
      intelligence: 62,
      politics: 57,
      charm: 74,
      fame: 16,
      gold: 260,
    },
    stamina: 80,
    biography: "熟悉来往旅客与城内传闻的宿场掌柜。",
    availableFunctions: [],
    skills: {
      ashigaru: 0,
      horse: 0,
      teppo: 0,
      navy: 0,
      archery: 0,
      martial: 0,
      military: 0,
      ninjutsu: 0,
      construction: 0,
      development: 1,
      mining: 0,
      arithmetic: 2,
      etiquette: 3,
      rhetoric: 3,
      tea: 2,
      medicine: 1,
    },
  },
];

export const prototypeCityNpcPools: CityNpcPoolDefinition[] = [
  {
    cityId: "city.kulan",
    residents: [
      {
        id: "city-npc.kulan.merchant_zhou",
        cityId: "city.kulan",
        name: "周掌柜",
        title: "盐商",
        personality: "精明",
        specialty: "交易",
        favorability: 0,
        activityWeight: {
          "tea-house": 20,
          tavern: 10,
          market: 60,
          street: 10,
        },
        dialoguePool: ["盐路一断，市价三日就要翻。"],
        intelPool: ["北边商路这几日有运盐队入城。"],
      },
      {
        id: "city-npc.kulan.scholar_he",
        cityId: "city.kulan",
        name: "何秀才",
        title: "落榜书生",
        personality: "傲气",
        specialty: "辩论",
        favorability: 0,
        activityWeight: {
          "tea-house": 50,
          tavern: 10,
          market: 10,
          street: 30,
        },
        dialoguePool: ["世人只问功名，不问文章。"],
        intelPool: ["城主府近日似乎在招募能写文书的人。"],
      },
      {
        id: "city-npc.kulan.wanderer_wu",
        cityId: "city.kulan",
        name: "老吴",
        title: "货郎",
        personality: "豪爽",
        specialty: "见闻",
        favorability: 0,
        activityWeight: {
          "tea-house": 25,
          tavern: 25,
          market: 30,
          street: 20,
        },
        dialoguePool: ["走南闯北的人，最重要的是眼睛和耳朵。"],
        intelPool: ["集市上有人在悄悄收购铁料。"],
      },
      {
        id: "city-npc.kulan.guard_lin",
        cityId: "city.kulan",
        name: "林镖头",
        title: "镖师",
        personality: "警惕",
        specialty: "江湖",
        favorability: 0,
        activityWeight: {
          "tea-house": 15,
          tavern: 35,
          market: 20,
          street: 30,
        },
        dialoguePool: ["喝酒可以，别在我背后站太久。"],
        intelPool: ["最近有人在打听出城商队的时辰。"],
      },
    ],
  },
];

export const prototypeCityPortraits: Record<string, string> = {
  "city.kulan": "顺天府",
};

export const prototypeCards: CardDefinition[] = [
  {
    id: "card.one_strike",
    name: "一齐攻击",
    category: "battle",
    skillDescription: "让部队集中攻击目标。",
    battlefieldDisplay: "战场全体突击",
    ammoCostText: "使用兵料：没有限制",
    cardImageId: "card-image.one_strike",
    logicNotes: "用于强制推进战斗回合的核心合战卡。",
  },
  {
    id: "card.secret_step",
    name: "强袭",
    category: "secret-technique",
    skillDescription: "以快速行动突破防线。",
    battlefieldDisplay: "战场快速突入",
    ammoCostText: "使用兵料：没有限制",
    cardImageId: "card-image.secret_step",
    logicNotes: "可作为忍术或特殊战术动作的基础。",
  },
  {
    id: "card.fire_attack",
    name: "火攻",
    category: "battle",
    skillDescription: "借火势破坏敌阵。",
    battlefieldDisplay: "战场火攻范围",
    ammoCostText: "使用兵料：需要火器或火计资源",
    cardImageId: "card-image.fire_attack",
    logicNotes: "后续可绑定天气、地形和火攻成功率。",
  },
];

export const prototypeValuables: ValuableItemDefinition[] = [
  {
    id: "item.sword.ogasa",
    name: "骨差",
    category: "weapon",
    price: 1,
    ownedCount: 1,
    kindText: "刀剑",
    itemImageId: "item-image.sword.ogasa",
    description: "无名匠所制的腰刀。",
  },
  {
    id: "item.armor.tetsu",
    name: "铁具足",
    category: "armor",
    price: 1,
    ownedCount: 1,
    kindText: "铠甲",
    itemImageId: "item-image.armor.tetsu",
    description: "基础护具，适合近身防护。",
  },
];
