import type {
  HistoricalCharacterRecord,
  HistoricalCityRoster,
} from "../domain/historical-character";
import type { CityNpcActivityLocationId } from "../domain/city-npc";
import type { SkillKey } from "../domain/character";

function character(
  record: Omit<
    HistoricalCharacterRecord,
    | "displayName"
    | "aliases"
    | "birthYear"
    | "deathYear"
    | "activeYears"
    | "relatedCityNodeIds"
    | "sourceNotes"
    | "status"
  > &
    Partial<
      Pick<
        HistoricalCharacterRecord,
        | "displayName"
        | "aliases"
        | "birthYear"
        | "deathYear"
        | "activeYears"
        | "relatedCityNodeIds"
        | "sourceNotes"
        | "status"
        | "cityNpcProfile"
        | "leaderResidenceProfile"
      >
    >
): HistoricalCharacterRecord {
  return {
    displayName: record.canonicalName,
    aliases: [],
    birthYear: null,
    deathYear: null,
    activeYears: { from: null, to: null },
    relatedCityNodeIds: [],
    sourceNotes: [],
    status: "candidate",
    ...record,
  };
}

function leaderResidenceProfile(input: {
  role: NonNullable<HistoricalCharacterRecord["leaderResidenceProfile"]>["residenceRole"];
  title: string;
  occupation: string;
  affiliationLabel: string;
  teachableSkillKeys?: SkillKey[];
  status?: NonNullable<HistoricalCharacterRecord["leaderResidenceProfile"]>["status"];
}): NonNullable<HistoricalCharacterRecord["leaderResidenceProfile"]> {
  return {
    eligible: true,
    status: input.status ?? "available",
    residenceRole: input.role,
    title: input.title,
    occupation: input.occupation,
    affiliationLabel: input.affiliationLabel,
    teachableSkillKeys: input.teachableSkillKeys ?? [],
  };
}

function cityNpcProfile(input: {
  title: string;
  personality: string;
  specialty: string;
  activity?: Partial<Record<CityNpcActivityLocationId, number>>;
  dialogue?: string[];
  intel?: string[];
  favorability?: number;
}): NonNullable<HistoricalCharacterRecord["cityNpcProfile"]> {
  return {
    enabled: true,
    title: input.title,
    personality: input.personality,
    specialty: input.specialty,
    favorability: input.favorability ?? 0,
    activityWeight: input.activity ?? {
      "tea-house": 25,
      tavern: 15,
      market: 20,
      street: 40,
    },
    dialoguePool: input.dialogue ?? ["如今兵荒马乱，城中人人都在等一个准信。"],
    intelPool: input.intel ?? ["城中人物往来频繁，军府与市井消息常常互相牵连。"],
  };
}

function militaryResidence(title: string, affiliationLabel: string) {
  return leaderResidenceProfile({
    role: "general",
    title,
    occupation: "武将",
    affiliationLabel,
    teachableSkillKeys: ["military", "martial", "horse"],
  });
}

function advisorResidence(title: string, affiliationLabel: string) {
  return leaderResidenceProfile({
    role: "advisor",
    title,
    occupation: "谋士",
    affiliationLabel,
    teachableSkillKeys: ["military", "rhetoric", "arithmetic"],
  });
}

const zhuYuanzhangCoreCharacters: HistoricalCharacterRecord[] = [
  character({
    id: "zyz.character.zhu_yuanzhang",
    canonicalName: "朱元璋",
    aliases: ["朱重八", "朱国瑞"],
    sourceType: "historical",
    priority: "P0",
    gender: "male",
    birthYear: 1328,
    deathYear: 1398,
    activeYears: { from: 1344, to: 1398 },
    factionId: "zhu_yuanzhang",
    factionName: "朱元璋早期集团",
    roleTags: ["protagonist", "commander"],
    stageTags: [
      "huangjue-temple",
      "wandering-monk",
      "haozhou-uprising",
      "guo-zixing-camp",
      "jianghuai-expansion",
      "jiqing-campaign",
    ],
    homeCityNodeId: "settlement.fenyang_province",
    currentCityNodeId: "settlement.fenyang_province",
    relatedCityNodeIds: [
      "settlement.taiping_province",
      "settlement.yingtian_province",
    ],
    shortBio: "钟离人，早年入皇觉寺，后投濠州郭子兴红巾军。",
    gameplayUse: "主角与早期成长线核心。",
  }),
  character({
    id: "zyz.character.ma_shi",
    canonicalName: "马氏",
    aliases: ["马姑娘", "马皇后"],
    sourceType: "historical",
    priority: "P0",
    gender: "female",
    birthYear: 1332,
    deathYear: 1382,
    activeYears: { from: 1352, to: 1382 },
    factionId: "guo_zixing",
    factionName: "濠州郭子兴集团",
    roleTags: ["family"],
    stageTags: ["guo-zixing-camp", "jianghuai-expansion", "early-yingtian"],
    homeCityNodeId: "settlement.fenyang_province",
    currentCityNodeId: "settlement.fenyang_province",
    shortBio: "郭子兴养女，朱元璋妻，早期濠州线的重要支持者。",
    gameplayUse: "婚姻、内宅、濠州政治支持线。",
  }),
  character({
    id: "zyz.character.guo_zixing",
    canonicalName: "郭子兴",
    sourceType: "historical",
    priority: "P0",
    gender: "male",
    deathYear: 1355,
    activeYears: { from: 1352, to: 1355 },
    factionId: "guo_zixing",
    factionName: "濠州郭子兴集团",
    roleTags: ["patron", "commander"],
    stageTags: ["haozhou-uprising", "guo-zixing-camp"],
    homeCityNodeId: "settlement.fenyang_province",
    currentCityNodeId: "settlement.fenyang_province",
    shortBio: "濠州红巾军首领，朱元璋早期上级与保护人。",
    gameplayUse: "投军、赏识、军府权力结构核心。",
  }),
  character({
    id: "zyz.character.guo_tianxu",
    canonicalName: "郭天叙",
    sourceType: "historical",
    priority: "P1",
    gender: "male",
    deathYear: 1355,
    factionId: "guo_zixing",
    factionName: "濠州郭子兴集团",
    roleTags: ["commander", "rival"],
    stageTags: ["guo-zixing-camp"],
    homeCityNodeId: "settlement.fenyang_province",
    currentCityNodeId: "settlement.fenyang_province",
    shortBio: "郭子兴之子，濠州集团继承和军府内斗线人物。",
    gameplayUse: "濠州军府矛盾、继承冲突。",
  }),
  character({
    id: "zyz.character.zhang_tianyou",
    canonicalName: "张天祐",
    sourceType: "historical",
    priority: "P1",
    gender: "male",
    factionId: "guo_zixing",
    factionName: "濠州郭子兴集团",
    roleTags: ["commander"],
    stageTags: ["guo-zixing-camp"],
    homeCityNodeId: "settlement.fenyang_province",
    currentCityNodeId: "settlement.fenyang_province",
    shortBio: "濠州军中人物，适合承接郭子兴集团内斗线。",
    gameplayUse: "军府内斗、濠州任务 NPC。",
  }),
  character({
    id: "zyz.character.sun_deya",
    canonicalName: "孙德崖",
    sourceType: "historical",
    priority: "P1",
    gender: "male",
    factionId: "guo_zixing",
    factionName: "濠州郭子兴集团",
    roleTags: ["rival", "commander"],
    stageTags: ["haozhou-uprising", "guo-zixing-camp"],
    homeCityNodeId: "settlement.fenyang_province",
    currentCityNodeId: "settlement.fenyang_province",
    shortBio: "濠州红巾军竞争派系人物。",
    gameplayUse: "早期政治压力、军营冲突。",
  }),
  character({
    id: "zyz.character.tang_he",
    canonicalName: "汤和",
    sourceType: "historical",
    priority: "P0",
    gender: "male",
    birthYear: 1326,
    deathYear: 1395,
    factionId: "zhu_yuanzhang",
    factionName: "朱元璋早期集团",
    roleTags: ["general", "patron"],
    stageTags: ["wandering-monk", "haozhou-uprising", "guo-zixing-camp"],
    homeCityNodeId: "settlement.fenyang_province",
    currentCityNodeId: "settlement.fenyang_province",
    relatedCityNodeIds: ["settlement.anqing_province"],
    shortBio: "朱元璋同乡，早期投军引路人。",
    gameplayUse: "引导投军、同乡关系、早期战斗教学。",
  }),
  character({
    id: "zyz.character.xu_da",
    canonicalName: "徐达",
    sourceType: "historical",
    priority: "P0",
    gender: "male",
    birthYear: 1332,
    deathYear: 1385,
    factionId: "zhu_yuanzhang",
    factionName: "朱元璋早期集团",
    roleTags: ["general", "commander"],
    stageTags: ["guo-zixing-camp", "jianghuai-expansion", "jiqing-campaign"],
    homeCityNodeId: "settlement.fenyang_province",
    currentCityNodeId: "settlement.fenyang_province",
    relatedCityNodeIds: [
      "settlement.luzhou_province",
      "settlement.taiping_province",
      "settlement.yingtian_province",
    ],
    shortBio: "朱元璋核心将领，后为明初名将。",
    gameplayUse: "主线军事伙伴、战斗型 NPC。",
  }),
  character({
    id: "zyz.character.chang_yuchun",
    canonicalName: "常遇春",
    sourceType: "historical",
    priority: "P1",
    gender: "male",
    birthYear: 1330,
    deathYear: 1369,
    factionId: "zhu_yuanzhang",
    factionName: "朱元璋早期集团",
    roleTags: ["general"],
    stageTags: ["jianghuai-expansion", "jiqing-campaign"],
    homeCityNodeId: "settlement.fenyang_province",
    currentCityNodeId: "settlement.taiping_province",
    shortBio: "朱元璋麾下猛将，适合在扩张阶段登场。",
    gameplayUse: "突击型武将、战斗事件。",
  }),
  character({
    id: "zyz.character.li_shanchang",
    canonicalName: "李善长",
    sourceType: "historical",
    priority: "P0",
    gender: "male",
    birthYear: 1314,
    deathYear: 1390,
    factionId: "zhu_yuanzhang",
    factionName: "朱元璋早期集团",
    roleTags: ["advisor", "civil-official"],
    stageTags: ["jianghuai-expansion", "jiqing-campaign", "early-yingtian"],
    homeCityNodeId: "settlement.luzhou_province",
    currentCityNodeId: "settlement.luzhou_province",
    relatedCityNodeIds: ["settlement.yingtian_province"],
    shortBio: "早期政务与后勤核心，后为朱元璋重要文臣。",
    gameplayUse: "政务、粮秣、城市治理教学。",
  }),
  character({
    id: "zyz.character.feng_guoyong",
    canonicalName: "冯国用",
    sourceType: "historical",
    priority: "P1",
    gender: "male",
    deathYear: 1358,
    factionId: "zhu_yuanzhang",
    factionName: "朱元璋早期集团",
    roleTags: ["advisor"],
    stageTags: ["jianghuai-expansion", "jiqing-campaign"],
    homeCityNodeId: "settlement.luzhou_province",
    currentCityNodeId: "settlement.luzhou_province",
    shortBio: "朱元璋早期谋士，冯胜之兄。",
    gameplayUse: "策略建议、军政支线。",
  }),
  character({
    id: "zyz.character.feng_sheng",
    canonicalName: "冯胜",
    sourceType: "historical",
    priority: "P1",
    gender: "male",
    deathYear: 1395,
    factionId: "zhu_yuanzhang",
    factionName: "朱元璋早期集团",
    roleTags: ["general"],
    stageTags: ["jianghuai-expansion", "jiqing-campaign"],
    homeCityNodeId: "settlement.luzhou_province",
    currentCityNodeId: "settlement.nanchang_province",
    shortBio: "朱元璋早期将领，后为明初功臣。",
    gameplayUse: "军事支线、后续北伐候选。",
  }),
  character({
    id: "zyz.character.deng_yu",
    canonicalName: "邓愈",
    sourceType: "historical",
    priority: "P1",
    gender: "male",
    birthYear: 1337,
    deathYear: 1377,
    factionId: "zhu_yuanzhang",
    factionName: "朱元璋早期集团",
    roleTags: ["general"],
    stageTags: ["jianghuai-expansion", "jiqing-campaign"],
    homeCityNodeId: "settlement.anqing_province",
    currentCityNodeId: "settlement.anqing_province",
    shortBio: "早期年轻将领，适合江淮西线登场。",
    gameplayUse: "年轻武将成长线。",
  }),
  character({
    id: "zyz.character.hu_dahai",
    canonicalName: "胡大海",
    sourceType: "historical",
    priority: "P1",
    gender: "male",
    deathYear: 1362,
    factionId: "zhu_yuanzhang",
    factionName: "朱元璋早期集团",
    roleTags: ["general"],
    stageTags: ["jianghuai-expansion", "jiqing-campaign"],
    homeCityNodeId: "settlement.taiping_province",
    currentCityNodeId: "settlement.taiping_province",
    shortBio: "朱元璋早期重要武将。",
    gameplayUse: "南下江南与攻城任务。",
  }),
  character({
    id: "zyz.character.zhou_dexing",
    canonicalName: "周德兴",
    sourceType: "historical",
    priority: "P1",
    gender: "male",
    birthYear: 1329,
    deathYear: 1392,
    factionId: "zhu_yuanzhang",
    factionName: "朱元璋早期集团",
    roleTags: ["general"],
    stageTags: ["guo-zixing-camp", "jianghuai-expansion"],
    homeCityNodeId: "settlement.fenyang_province",
    currentCityNodeId: "settlement.fenyang_province",
    shortBio: "淮西旧部，后为明初功臣。",
    gameplayUse: "濠州旧部、军营 NPC。",
  }),
  character({
    id: "zyz.character.guo_ying",
    canonicalName: "郭英",
    sourceType: "historical",
    priority: "P1",
    gender: "male",
    birthYear: 1335,
    deathYear: 1403,
    factionId: "zhu_yuanzhang",
    factionName: "朱元璋早期集团",
    roleTags: ["general"],
    stageTags: ["guo-zixing-camp", "jianghuai-expansion"],
    homeCityNodeId: "settlement.fenyang_province",
    currentCityNodeId: "settlement.fenyang_province",
    shortBio: "淮西武将，适合作为早期亲军人物。",
    gameplayUse: "护卫、亲军、巡逻任务。",
  }),
  character({
    id: "zyz.character.geng_bingwen",
    canonicalName: "耿炳文",
    sourceType: "historical",
    priority: "P1",
    gender: "male",
    birthYear: 1334,
    deathYear: 1403,
    factionId: "zhu_yuanzhang",
    factionName: "朱元璋早期集团",
    roleTags: ["general"],
    stageTags: ["jianghuai-expansion", "jiqing-campaign"],
    homeCityNodeId: "settlement.luzhou_province",
    currentCityNodeId: "settlement.luzhou_province",
    shortBio: "稳健型将领，适合守城和后勤线。",
    gameplayUse: "守备、训练、城防任务。",
  }),
  character({
    id: "zyz.character.li_wenzhong",
    canonicalName: "李文忠",
    sourceType: "historical",
    priority: "P1",
    gender: "male",
    birthYear: 1339,
    deathYear: 1384,
    factionId: "zhu_yuanzhang",
    factionName: "朱元璋早期集团",
    roleTags: ["family", "general"],
    stageTags: ["jianghuai-expansion", "jiqing-campaign"],
    homeCityNodeId: "settlement.luzhou_province",
    currentCityNodeId: "settlement.luzhou_province",
    shortBio: "朱元璋外甥，后为重要将领。",
    gameplayUse: "亲族少年将领线。",
  }),
  character({
    id: "zyz.character.zhu_wenzheng",
    canonicalName: "朱文正",
    sourceType: "historical",
    priority: "P1",
    gender: "male",
    deathYear: 1365,
    factionId: "zhu_yuanzhang",
    factionName: "朱元璋早期集团",
    roleTags: ["family", "general"],
    stageTags: ["jiqing-campaign", "early-yingtian"],
    homeCityNodeId: "settlement.nanchang_province",
    currentCityNodeId: "settlement.nanchang_province",
    shortBio: "朱元璋侄，洪都守城线关键人物。",
    gameplayUse: "后续洪都守城剧情，不在和尚期默认出场。",
  }),
  character({
    id: "zyz.character.hua_yun",
    canonicalName: "花云",
    sourceType: "historical",
    priority: "P1",
    gender: "male",
    deathYear: 1360,
    factionId: "zhu_yuanzhang",
    factionName: "朱元璋早期集团",
    roleTags: ["general"],
    stageTags: ["jianghuai-expansion", "jiqing-campaign"],
    homeCityNodeId: "settlement.taiping_province",
    currentCityNodeId: "settlement.taiping_province",
    shortBio: "朱元璋早期勇将。",
    gameplayUse: "太平路、江防、忠烈剧情。",
  }),
  character({
    id: "zyz.character.han_liner",
    canonicalName: "韩林儿",
    aliases: ["小明王"],
    sourceType: "historical",
    priority: "P0",
    gender: "male",
    deathYear: 1366,
    factionId: "xiaoming_song",
    factionName: "小明王宋",
    roleTags: ["commander", "event-only"],
    stageTags: ["hongjin-song", "guo-zixing-camp", "jianghuai-expansion"],
    homeCityNodeId: "settlement.tieling_province",
    currentCityNodeId: "settlement.tieling_province",
    relatedCityNodeIds: ["settlement.runing_province"],
    shortBio: "红巾军拥立的小明王，名义上的宋政权君主。",
    gameplayUse: "名义正统、红巾政权线。",
  }),
  character({
    id: "zyz.character.liu_futong",
    canonicalName: "刘福通",
    sourceType: "historical",
    priority: "P0",
    gender: "male",
    deathYear: 1363,
    factionId: "xiaoming_song",
    factionName: "小明王宋",
    roleTags: ["commander"],
    stageTags: ["hongjin-song", "jianghuai-expansion"],
    homeCityNodeId: "settlement.tieling_province",
    currentCityNodeId: "settlement.tieling_province",
    relatedCityNodeIds: ["settlement.runing_province"],
    shortBio: "红巾军重要首领，小明王政权实际主导人物。",
    gameplayUse: "安丰/汝宁红巾主线。",
  }),
  character({
    id: "zyz.character.han_shantong",
    canonicalName: "韩山童",
    sourceType: "historical",
    priority: "P1",
    gender: "male",
    deathYear: 1351,
    factionId: "xiaoming_song",
    factionName: "小明王宋",
    roleTags: ["event-only"],
    stageTags: ["hongjin-song"],
    homeCityNodeId: "settlement.runing_province",
    currentCityNodeId: "settlement.runing_province",
    shortBio: "红巾起事源头人物，韩林儿之父。",
    gameplayUse: "背景事件、红巾正统叙事。",
  }),
  character({
    id: "zyz.character.du_zundao",
    canonicalName: "杜遵道",
    sourceType: "historical",
    priority: "P1",
    gender: "male",
    factionId: "xiaoming_song",
    factionName: "小明王宋",
    roleTags: ["civil-official"],
    stageTags: ["hongjin-song"],
    homeCityNodeId: "settlement.runing_province",
    currentCityNodeId: "settlement.runing_province",
    shortBio: "小明王宋政权人物。",
    gameplayUse: "宋政权文臣与政务事件。",
  }),
  character({
    id: "zyz.character.sheng_wenyu",
    canonicalName: "盛文郁",
    sourceType: "historical",
    priority: "P1",
    gender: "male",
    factionId: "xiaoming_song",
    factionName: "小明王宋",
    roleTags: ["civil-official"],
    stageTags: ["hongjin-song"],
    homeCityNodeId: "settlement.tieling_province",
    currentCityNodeId: "settlement.tieling_province",
    shortBio: "小明王宋政权人物。",
    gameplayUse: "安丰宋政权背景人物。",
  }),
  character({
    id: "zyz.character.bai_buxin",
    canonicalName: "白不信",
    sourceType: "historical",
    priority: "P2",
    gender: "male",
    factionId: "xiaoming_song",
    factionName: "小明王宋",
    roleTags: ["general"],
    stageTags: ["hongjin-song"],
    homeCityNodeId: "settlement.runing_province",
    currentCityNodeId: "settlement.runing_province",
    shortBio: "宋线红巾将领。",
    gameplayUse: "红巾军支线与地方军事 NPC。",
  }),
  character({
    id: "zyz.character.zhang_shicheng",
    canonicalName: "张士诚",
    sourceType: "historical",
    priority: "P0",
    gender: "male",
    birthYear: 1321,
    deathYear: 1367,
    factionId: "zhang_shicheng",
    factionName: "张士诚周",
    roleTags: ["rival", "commander"],
    stageTags: ["jianghuai-expansion", "late-context-only"],
    homeCityNodeId: "settlement.huaian_province",
    currentCityNodeId: "settlement.yangzhou_province",
    relatedCityNodeIds: [
      "settlement.huaian_province",
      "settlement.suzhou_province",
    ],
    shortBio: "盐徒起事首领，淮东与江南竞争势力核心。",
    gameplayUse: "高邮、扬州、平江线主要竞争者。",
  }),
  character({
    id: "zyz.character.zhang_shide",
    canonicalName: "张士德",
    sourceType: "historical",
    priority: "P1",
    gender: "male",
    factionId: "zhang_shicheng",
    factionName: "张士诚周",
    roleTags: ["general", "family"],
    stageTags: ["jianghuai-expansion", "late-context-only"],
    homeCityNodeId: "settlement.yangzhou_province",
    currentCityNodeId: "settlement.yangzhou_province",
    shortBio: "张士诚之弟，周政权重要军事人物。",
    gameplayUse: "张士诚阵营军事 NPC。",
  }),
  character({
    id: "zyz.character.zhang_shixin",
    canonicalName: "张士信",
    sourceType: "historical",
    priority: "P1",
    gender: "male",
    factionId: "zhang_shicheng",
    factionName: "张士诚周",
    roleTags: ["general", "family"],
    stageTags: ["jianghuai-expansion", "late-context-only"],
    homeCityNodeId: "settlement.suzhou_province",
    currentCityNodeId: "settlement.suzhou_province",
    shortBio: "张士诚之弟，江南线人物。",
    gameplayUse: "平江/苏州后续章节。",
  }),
  character({
    id: "zyz.character.li_bosheng",
    canonicalName: "李伯升",
    sourceType: "historical",
    priority: "P1",
    gender: "male",
    factionId: "zhang_shicheng",
    factionName: "张士诚周",
    roleTags: ["general"],
    stageTags: ["jianghuai-expansion"],
    homeCityNodeId: "settlement.yangzhou_province",
    currentCityNodeId: "settlement.yangzhou_province",
    shortBio: "张士诚重要将领。",
    gameplayUse: "淮东敌对将领。",
  }),
  character({
    id: "zyz.character.lv_zhen",
    canonicalName: "吕珍",
    sourceType: "historical",
    priority: "P1",
    gender: "male",
    factionId: "zhang_shicheng",
    factionName: "张士诚周",
    roleTags: ["general"],
    stageTags: ["jianghuai-expansion"],
    homeCityNodeId: "settlement.huaian_province",
    currentCityNodeId: "settlement.huaian_province",
    shortBio: "张士诚将领，和安丰、小明王线有关。",
    gameplayUse: "高邮/安丰军事事件。",
    sourceNotes: ["当前模组 NPC 抽取中未见，需补。"],
  }),
  character({
    id: "zyz.character.panyuan_shao",
    canonicalName: "潘元绍",
    sourceType: "historical",
    priority: "P2",
    gender: "male",
    factionId: "zhang_shicheng",
    factionName: "张士诚周",
    roleTags: ["civil-official", "general"],
    stageTags: ["jianghuai-expansion"],
    homeCityNodeId: "settlement.huaian_province",
    currentCityNodeId: "settlement.huaian_province",
    shortBio: "张士诚阵营人物。",
    gameplayUse: "高邮/淮东支线。",
  }),
  character({
    id: "zyz.character.rao_jie",
    canonicalName: "饶介",
    sourceType: "historical",
    priority: "P2",
    gender: "male",
    factionId: "zhang_shicheng",
    factionName: "张士诚周",
    roleTags: ["civil-official"],
    stageTags: ["jianghuai-expansion"],
    homeCityNodeId: "settlement.yangzhou_province",
    currentCityNodeId: "settlement.yangzhou_province",
    shortBio: "张士诚阵营淮南人物。",
    gameplayUse: "扬州政务和文人支线。",
  }),
  character({
    id: "zyz.character.chen_youliang",
    canonicalName: "陈友谅",
    sourceType: "historical",
    priority: "P0",
    gender: "male",
    birthYear: 1320,
    deathYear: 1363,
    factionId: "chen_youliang",
    factionName: "陈友谅汉",
    roleTags: ["rival", "commander"],
    stageTags: ["late-context-only"],
    homeCityNodeId: "settlement.wuchang_province",
    currentCityNodeId: "settlement.wuchang_province",
    relatedCityNodeIds: ["settlement.nanchang_province"],
    shortBio: "陈汉政权核心，后期主要强敌。",
    gameplayUse: "远方威胁、后续汉吴对抗主线。",
  }),
  character({
    id: "zyz.character.zhang_dingbian",
    canonicalName: "张定边",
    sourceType: "historical",
    priority: "P0",
    gender: "male",
    factionId: "chen_youliang",
    factionName: "陈友谅汉",
    roleTags: ["general", "enemy"],
    stageTags: ["late-context-only"],
    homeCityNodeId: "settlement.wuchang_province",
    currentCityNodeId: "settlement.wuchang_province",
    shortBio: "陈友谅麾下猛将。",
    gameplayUse: "后续鄱阳湖和陈汉军事线。",
  }),
  character({
    id: "zyz.character.xu_shouhui",
    canonicalName: "徐寿辉",
    sourceType: "historical",
    priority: "P1",
    gender: "male",
    deathYear: 1360,
    factionId: "chen_youliang",
    factionName: "天完/陈汉前身",
    roleTags: ["commander", "event-only"],
    stageTags: ["late-context-only"],
    homeCityNodeId: "settlement.wuchang_province",
    currentCityNodeId: "settlement.wuchang_province",
    shortBio: "天完政权君主，陈友谅崛起背景人物。",
    gameplayUse: "陈汉前史事件。",
  }),
  character({
    id: "zyz.character.zou_pusheng",
    canonicalName: "邹普胜",
    sourceType: "historical",
    priority: "P1",
    gender: "male",
    factionId: "chen_youliang",
    factionName: "天完/陈汉前身",
    roleTags: ["advisor"],
    stageTags: ["late-context-only"],
    homeCityNodeId: "settlement.wuchang_province",
    currentCityNodeId: "settlement.wuchang_province",
    shortBio: "天完/陈汉相关人物。",
    gameplayUse: "陈友谅势力政务和宗教色彩支线。",
    sourceNotes: ["当前模组 NPC 抽取中未见，需补。"],
  }),
  character({
    id: "zyz.character.ming_yuzhen",
    canonicalName: "明玉珍",
    sourceType: "historical",
    priority: "P1",
    gender: "male",
    birthYear: 1331,
    deathYear: 1366,
    factionId: "ming_yuzhen",
    factionName: "明玉珍夏",
    roleTags: ["commander"],
    stageTags: ["late-context-only"],
    homeCityNodeId: "settlement.chongqing_province",
    currentCityNodeId: "settlement.chendu_province",
    relatedCityNodeIds: ["settlement.chongqing_province"],
    shortBio: "西南夏政权核心。",
    gameplayUse: "西南远方势力、后续外交和传闻。",
  }),
  character({
    id: "zyz.character.wan_sheng",
    canonicalName: "万胜",
    sourceType: "historical",
    priority: "P2",
    gender: "male",
    factionId: "ming_yuzhen",
    factionName: "明玉珍夏",
    roleTags: ["general"],
    stageTags: ["late-context-only"],
    homeCityNodeId: "settlement.chongqing_province",
    currentCityNodeId: "settlement.chongqing_province",
    shortBio: "明玉珍势力将领。",
    gameplayUse: "西南军事背景。",
  }),
  character({
    id: "zyz.character.fang_guozhen",
    canonicalName: "方国珍",
    sourceType: "historical",
    priority: "P1",
    gender: "male",
    birthYear: 1319,
    deathYear: 1374,
    factionId: "fang_guozhen",
    factionName: "方国珍浙东",
    roleTags: ["commander", "rival"],
    stageTags: ["late-context-only"],
    homeCityNodeId: "settlement.ningbo_province",
    currentCityNodeId: "settlement.ningbo_province",
    relatedCityNodeIds: ["settlement.wenzhou_province"],
    shortBio: "浙东海上势力核心。",
    gameplayUse: "海上势力、浙东竞争者。",
  }),
  character({
    id: "zyz.character.fang_li",
    canonicalName: "方礼",
    sourceType: "historical",
    priority: "P2",
    gender: "male",
    factionId: "fang_guozhen",
    factionName: "方国珍浙东",
    roleTags: ["general"],
    stageTags: ["late-context-only"],
    homeCityNodeId: "settlement.wenzhou_province",
    currentCityNodeId: "settlement.wenzhou_province",
    shortBio: "方国珍势力人物。",
    gameplayUse: "浙东支线。",
  }),
  character({
    id: "zyz.character.chen_youding",
    canonicalName: "陈友定",
    sourceType: "historical",
    priority: "P1",
    gender: "male",
    deathYear: 1368,
    factionId: "chen_youding",
    factionName: "福建陈友定",
    roleTags: ["commander", "enemy"],
    stageTags: ["late-context-only"],
    homeCityNodeId: "settlement.fuzhou_province",
    currentCityNodeId: "settlement.fuzhou_province",
    relatedCityNodeIds: [
      "settlement.quanzhou_province",
      "settlement.zhangzhou_province",
    ],
    shortBio: "元末福建地方军政人物。",
    gameplayUse: "福建元军和后续统一线。",
  }),
  character({
    id: "zyz.character.toghon_temur",
    canonicalName: "妥懽帖睦尔",
    aliases: ["元顺帝"],
    sourceType: "historical",
    priority: "P0",
    gender: "male",
    birthYear: 1320,
    deathYear: 1370,
    factionId: "yuan_court",
    factionName: "元廷中央",
    roleTags: ["commander", "event-only"],
    stageTags: ["late-context-only"],
    homeCityNodeId: "settlement.shuntian_province",
    currentCityNodeId: "settlement.shuntian_province",
    shortBio: "元朝皇帝，元末天下秩序崩坏的中央象征。",
    gameplayUse: "天下背景、诏令、远方政治压力。",
  }),
  character({
    id: "zyz.character.ayushiridara",
    canonicalName: "爱猷识理答腊",
    sourceType: "historical",
    priority: "P1",
    gender: "male",
    birthYear: 1338,
    deathYear: 1378,
    factionId: "yuan_court",
    factionName: "元廷中央",
    roleTags: ["family", "event-only"],
    stageTags: ["late-context-only"],
    homeCityNodeId: "settlement.shuntian_province",
    currentCityNodeId: "settlement.shuntian_province",
    shortBio: "元顺帝皇太子。",
    gameplayUse: "元廷政局背景。",
  }),
  character({
    id: "zyz.character.chaghan_temur",
    canonicalName: "察罕帖木儿",
    sourceType: "historical",
    priority: "P1",
    gender: "male",
    deathYear: 1362,
    factionId: "yuan_henan_shandong",
    factionName: "河南山东元军",
    roleTags: ["commander", "enemy"],
    stageTags: ["late-context-only"],
    homeCityNodeId: "settlement.kaifeng_province",
    currentCityNodeId: "settlement.kaifeng_province",
    relatedCityNodeIds: ["settlement.henan_province"],
    shortBio: "元末北方名将，扩廓帖木儿养父。",
    gameplayUse: "北方元军压力线。",
  }),
  character({
    id: "zyz.character.koketumur",
    canonicalName: "扩廓帖木儿",
    aliases: ["王保保"],
    sourceType: "historical",
    priority: "P1",
    gender: "male",
    deathYear: 1375,
    factionId: "yuan_henan_shandong",
    factionName: "河南山东元军",
    roleTags: ["commander", "enemy"],
    stageTags: ["late-context-only"],
    homeCityNodeId: "settlement.kaifeng_province",
    currentCityNodeId: "settlement.kaifeng_province",
    relatedCityNodeIds: ["settlement.taiyuan_province"],
    shortBio: "元末重要军事人物，后期北方强敌。",
    gameplayUse: "后续北伐强敌。",
  }),
  character({
    id: "zyz.character.li_siqi",
    canonicalName: "李思齐",
    sourceType: "historical",
    priority: "P1",
    gender: "male",
    factionId: "yuan_shaanxi_gansu",
    factionName: "陕西甘肃元军",
    roleTags: ["commander", "enemy"],
    stageTags: ["late-context-only"],
    homeCityNodeId: "settlement.gongchang_province",
    currentCityNodeId: "settlement.gongchang_province",
    relatedCityNodeIds: ["settlement.lanzhou_province"],
    shortBio: "元末陕西重要军政人物。",
    gameplayUse: "西北元军和后续北伐线。",
  }),
  character({
    id: "zyz.character.zhang_liangbi",
    canonicalName: "张良弼",
    sourceType: "historical",
    priority: "P1",
    gender: "male",
    factionId: "yuan_shaanxi_gansu",
    factionName: "陕西甘肃元军",
    roleTags: ["commander", "enemy"],
    stageTags: ["late-context-only"],
    homeCityNodeId: "settlement.xian_province",
    currentCityNodeId: "settlement.xian_province",
    shortBio: "陕西元军势力人物。",
    gameplayUse: "关中、西北压力线。",
  }),
  character({
    id: "zyz.character.huangjue_abbot",
    canonicalName: "皇觉寺住持",
    sourceType: "composite",
    priority: "P0",
    gender: "male",
    factionId: "temple_commoner",
    factionName: "寺院与民间",
    roleTags: ["monk"],
    stageTags: ["huangjue-temple"],
    homeCityNodeId: "settlement.fenyang_province",
    currentCityNodeId: "settlement.fenyang_province",
    shortBio: "用于承载皇觉寺生活、出家、饥荒背景的合成人物。",
    gameplayUse: "新手寺院任务、朱元璋和尚时期日常。",
  }),
  character({
    id: "zyz.character.temple_senior_monk",
    canonicalName: "寺中师兄",
    sourceType: "fictionalized",
    priority: "P1",
    gender: "male",
    factionId: "temple_commoner",
    factionName: "寺院与民间",
    roleTags: ["monk"],
    stageTags: ["huangjue-temple"],
    homeCityNodeId: "settlement.fenyang_province",
    currentCityNodeId: "settlement.fenyang_province",
    shortBio: "寺院日常 NPC，用于表现饥荒和寺院困境。",
    gameplayUse: "寺院对话、杂务、基础教学。",
  }),
  character({
    id: "zyz.character.zhongli_elder",
    canonicalName: "钟离父老",
    sourceType: "composite",
    priority: "P1",
    gender: "unknown",
    factionId: "temple_commoner",
    factionName: "寺院与民间",
    roleTags: ["local-elite", "commoner"],
    stageTags: ["huangjue-temple", "wandering-monk"],
    homeCityNodeId: "settlement.fenyang_province",
    currentCityNodeId: "settlement.fenyang_province",
    shortBio: "钟离乡土记忆与灾荒背景的合成人物。",
    gameplayUse: "乡村传闻、家破背景、民生任务。",
  }),
];

const zhuYuanzhangAdditionalCharacters: HistoricalCharacterRecord[] = [
  character({
    id: "zyz.character.liu_ji",
    canonicalName: "刘基",
    aliases: ["刘伯温"],
    sourceType: "historical",
    priority: "P1",
    gender: "male",
    birthYear: 1311,
    deathYear: 1375,
    factionId: "zhu_yuanzhang",
    factionName: "朱元璋早期集团",
    roleTags: ["advisor", "civil-official"],
    stageTags: ["early-yingtian", "late-context-only"],
    homeCityNodeId: "settlement.wenzhou_province",
    currentCityNodeId: "settlement.yingtian_province",
    relatedCityNodeIds: ["settlement.wenzhou_province"],
    shortBio: "浙东名士，后为朱元璋重要谋臣。",
    gameplayUse: "后续应天谋臣府邸、战略推演、奇谋事件。",
    cityNpcProfile: cityNpcProfile({
      title: "浙东名士",
      personality: "深沉",
      specialty: "谋略",
      activity: { "tea-house": 45, street: 25, market: 25, tavern: 5 },
    }),
    leaderResidenceProfile: advisorResidence("谋臣", "朱元璋幕府"),
  }),
  character({
    id: "zyz.character.song_lian",
    canonicalName: "宋濂",
    sourceType: "historical",
    priority: "P2",
    gender: "male",
    birthYear: 1310,
    deathYear: 1381,
    factionId: "zhu_yuanzhang",
    factionName: "朱元璋早期集团",
    roleTags: ["civil-official", "advisor"],
    stageTags: ["early-yingtian", "late-context-only"],
    homeCityNodeId: "settlement.shaoxing_province",
    currentCityNodeId: "settlement.yingtian_province",
    shortBio: "浙东文士，后入明初文臣系统。",
    gameplayUse: "文书、礼制、史馆与教育线。",
    cityNpcProfile: cityNpcProfile({ title: "文士", personality: "谨严", specialty: "文书" }),
    leaderResidenceProfile: advisorResidence("知制诰", "朱元璋幕府"),
  }),
  character({
    id: "zyz.character.zhu_sheng",
    canonicalName: "朱升",
    sourceType: "historical",
    priority: "P2",
    gender: "male",
    factionId: "zhu_yuanzhang",
    factionName: "朱元璋早期集团",
    roleTags: ["advisor", "civil-official"],
    stageTags: ["early-yingtian", "late-context-only"],
    homeCityNodeId: "settlement.yingtian_province",
    currentCityNodeId: "settlement.yingtian_province",
    shortBio: "朱元璋早期谋士，适合承载高筑墙、广积粮、缓称王方向。",
    gameplayUse: "战略路线建议、称王节奏和民政路线。",
    cityNpcProfile: cityNpcProfile({ title: "幕府谋士", personality: "稳健", specialty: "战略" }),
    leaderResidenceProfile: advisorResidence("中顺大夫", "朱元璋幕府"),
  }),
  character({
    id: "zyz.character.miao_daheng",
    canonicalName: "缪大亨",
    sourceType: "historical",
    priority: "P2",
    gender: "male",
    factionId: "zhu_yuanzhang",
    factionName: "朱元璋早期集团",
    roleTags: ["general"],
    stageTags: ["jianghuai-expansion", "jiqing-campaign"],
    homeCityNodeId: "settlement.luzhou_province",
    currentCityNodeId: "settlement.luzhou_province",
    shortBio: "淮西武将，适合作为军府将领池候选。",
    gameplayUse: "军府训练、巡营和战斗随从。",
    cityNpcProfile: cityNpcProfile({ title: "武将", personality: "沉稳", specialty: "军务" }),
    leaderResidenceProfile: militaryResidence("同佥枢密院事", "朱元璋军府"),
  }),
  character({
    id: "zyz.character.mu_ying",
    canonicalName: "沐英",
    sourceType: "historical",
    priority: "P2",
    gender: "male",
    birthYear: 1345,
    deathYear: 1392,
    factionId: "zhu_yuanzhang",
    factionName: "朱元璋早期集团",
    roleTags: ["family", "general"],
    stageTags: ["late-context-only"],
    homeCityNodeId: "settlement.taiping_province",
    currentCityNodeId: "settlement.yingtian_province",
    shortBio: "朱元璋养子，和尚期不宜过早登场，后续可进入亲军线。",
    gameplayUse: "少年亲信、后续西南线伏笔。",
    cityNpcProfile: cityNpcProfile({ title: "亲军少年", personality: "坚忍", specialty: "护卫" }),
    leaderResidenceProfile: militaryResidence("帐前都尉", "朱元璋亲军"),
  }),
  character({
    id: "zyz.character.fu_youdej",
    canonicalName: "傅友德",
    sourceType: "historical",
    priority: "P2",
    gender: "male",
    deathYear: 1394,
    factionId: "zhu_yuanzhang",
    factionName: "朱元璋早期集团",
    roleTags: ["general"],
    stageTags: ["late-context-only"],
    homeCityNodeId: "settlement.anqing_province",
    currentCityNodeId: "settlement.yingtian_province",
    shortBio: "明初名将，早期可作为后续加入候选。",
    gameplayUse: "后续强力武将、北伐与西南战线。",
    cityNpcProfile: cityNpcProfile({ title: "武将", personality: "果敢", specialty: "野战" }),
    leaderResidenceProfile: militaryResidence("雄武卫指挥使", "朱元璋军府"),
  }),
  character({
    id: "zyz.character.guo_xing",
    canonicalName: "郭兴",
    sourceType: "historical",
    priority: "P2",
    gender: "male",
    factionId: "zhu_yuanzhang",
    factionName: "朱元璋早期集团",
    roleTags: ["general"],
    stageTags: ["guo-zixing-camp", "jianghuai-expansion"],
    homeCityNodeId: "settlement.fenyang_province",
    currentCityNodeId: "settlement.fenyang_province",
    shortBio: "淮西将领，适合濠州亲军池。",
    gameplayUse: "濠州巡营、训练、亲军任务。",
    cityNpcProfile: cityNpcProfile({ title: "亲军将领", personality: "谨慎", specialty: "巡营" }),
    leaderResidenceProfile: militaryResidence("管军总管", "濠州军府"),
  }),
  character({
    id: "zyz.character.ding_pulang",
    canonicalName: "丁普郎",
    sourceType: "historical",
    priority: "P2",
    gender: "male",
    factionId: "zhu_yuanzhang",
    factionName: "朱元璋早期集团",
    roleTags: ["general"],
    stageTags: ["jianghuai-expansion"],
    homeCityNodeId: "settlement.luzhou_province",
    currentCityNodeId: "settlement.luzhou_province",
    shortBio: "朱元璋阵营将领候选。",
    gameplayUse: "江淮军府支线。",
    cityNpcProfile: cityNpcProfile({ title: "军府将领", personality: "直率", specialty: "步军" }),
    leaderResidenceProfile: militaryResidence("枢密院同知", "朱元璋军府"),
  }),
  character({
    id: "zyz.character.haozhou_salt_runner",
    canonicalName: "濠州盐贩",
    sourceType: "fictionalized",
    priority: "P3",
    gender: "unknown",
    factionId: "temple_commoner",
    factionName: "寺院与民间",
    roleTags: ["merchant", "rumor-source"],
    stageTags: ["huangjue-temple", "haozhou-uprising"],
    homeCityNodeId: "settlement.fenyang_province",
    currentCityNodeId: "settlement.fenyang_province",
    shortBio: "用于承载盐路、民间消息和城市经济的虚构功能 NPC。",
    gameplayUse: "城市角色池、市场传闻、早期经济任务。",
    cityNpcProfile: cityNpcProfile({
      title: "盐贩",
      personality: "精明",
      specialty: "市井",
      activity: { market: 55, tavern: 20, street: 20, "tea-house": 5 },
    }),
  }),
  character({
    id: "zyz.character.haozhou_red_turban_scout",
    canonicalName: "濠州红巾哨骑",
    sourceType: "fictionalized",
    priority: "P3",
    gender: "male",
    factionId: "guo_zixing",
    factionName: "濠州郭子兴集团",
    roleTags: ["commoner", "rumor-source"],
    stageTags: ["haozhou-uprising", "guo-zixing-camp"],
    homeCityNodeId: "settlement.fenyang_province",
    currentCityNodeId: "settlement.fenyang_province",
    shortBio: "用于承载红巾军基层情报的功能 NPC。",
    gameplayUse: "街市情报、巡逻任务、军府前置任务。",
    cityNpcProfile: cityNpcProfile({
      title: "红巾哨骑",
      personality: "警觉",
      specialty: "斥候",
      activity: { street: 55, tavern: 20, market: 15, "tea-house": 10 },
    }),
  }),
  character({
    id: "zyz.character.hu_weiyong",
    canonicalName: "胡惟庸",
    sourceType: "historical",
    priority: "P2",
    gender: "male",
    deathYear: 1380,
    factionId: "zhu_yuanzhang",
    factionName: "朱元璋早期集团",
    roleTags: ["civil-official", "advisor"],
    stageTags: ["early-yingtian", "late-context-only"],
    homeCityNodeId: "settlement.luzhou_province",
    currentCityNodeId: "settlement.yingtian_province",
    shortBio: "后期重要文臣，早期只作为低权重幕僚候选。",
    gameplayUse: "幕府文书、后续政治风险伏笔。",
    cityNpcProfile: cityNpcProfile({ title: "奏差", personality: "机敏", specialty: "文案" }),
    leaderResidenceProfile: advisorResidence("元帅府奏差", "朱元璋幕府"),
  }),
  character({
    id: "zyz.character.lan_yu",
    canonicalName: "蓝玉",
    sourceType: "historical",
    priority: "P2",
    gender: "male",
    deathYear: 1393,
    factionId: "zhu_yuanzhang",
    factionName: "朱元璋早期集团",
    roleTags: ["general"],
    stageTags: ["late-context-only"],
    homeCityNodeId: "settlement.yingtian_province",
    currentCityNodeId: "settlement.yingtian_province",
    shortBio: "后续名将，和尚期不默认正面登场。",
    gameplayUse: "后期亲军与北伐线候选。",
    cityNpcProfile: cityNpcProfile({ title: "年轻武将", personality: "骁悍", specialty: "骑战" }),
    leaderResidenceProfile: militaryResidence("指挥使", "朱元璋军府"),
  }),
  character({
    id: "zyz.character.han_tong",
    canonicalName: "韩童",
    sourceType: "historical",
    priority: "P2",
    gender: "male",
    factionId: "xiaoming_song",
    factionName: "小明王宋",
    roleTags: ["family", "event-only"],
    stageTags: ["hongjin-song"],
    homeCityNodeId: "settlement.tieling_province",
    currentCityNodeId: "settlement.tieling_province",
    shortBio: "小明王宋线人物，可作为韩氏宗族背景。",
    gameplayUse: "宋政权宗族、正统叙事背景。",
    cityNpcProfile: cityNpcProfile({ title: "宋室宗族", personality: "谨弱", specialty: "礼制" }),
  }),
  character({
    id: "zyz.character.tian_feng",
    canonicalName: "田丰",
    sourceType: "historical",
    priority: "P2",
    gender: "male",
    factionId: "xiaoming_song",
    factionName: "小明王宋",
    roleTags: ["civil-official", "commander"],
    stageTags: ["hongjin-song"],
    homeCityNodeId: "settlement.kaifeng_province",
    currentCityNodeId: "settlement.kaifeng_province",
    shortBio: "宋线北方人物。",
    gameplayUse: "山东河南红巾支线与远方战报。",
    cityNpcProfile: cityNpcProfile({ title: "宋军官员", personality: "急切", specialty: "军政" }),
  }),
  character({
    id: "zyz.character.wang_shicheng_song",
    canonicalName: "王士诚",
    sourceType: "historical",
    priority: "P2",
    gender: "male",
    factionId: "xiaoming_song",
    factionName: "小明王宋",
    roleTags: ["general"],
    stageTags: ["hongjin-song"],
    homeCityNodeId: "settlement.kaifeng_province",
    currentCityNodeId: "settlement.kaifeng_province",
    shortBio: "宋线红巾将领。",
    gameplayUse: "北方红巾战报和支线。",
    cityNpcProfile: cityNpcProfile({ title: "红巾将领", personality: "强硬", specialty: "军务" }),
  }),
  character({
    id: "zyz.character.zhang_tianyou_zhou",
    canonicalName: "张天佑",
    sourceType: "historical",
    priority: "P2",
    gender: "male",
    factionId: "zhang_shicheng",
    factionName: "张士诚周",
    roleTags: ["family"],
    stageTags: ["late-context-only"],
    homeCityNodeId: "settlement.yangzhou_province",
    currentCityNodeId: "settlement.yangzhou_province",
    shortBio: "张士诚阵营宗族人物。",
    gameplayUse: "周政权继承与内廷背景。",
    cityNpcProfile: cityNpcProfile({ title: "周太子", personality: "矜持", specialty: "宗族" }),
    leaderResidenceProfile: leaderResidenceProfile({
      role: "family",
      title: "太子",
      occupation: "宗族",
      affiliationLabel: "张士诚周",
      teachableSkillKeys: ["etiquette", "rhetoric"],
    }),
  }),
  character({
    id: "zyz.character.zhang_shiyi",
    canonicalName: "张士义",
    sourceType: "historical",
    priority: "P2",
    gender: "male",
    factionId: "zhang_shicheng",
    factionName: "张士诚周",
    roleTags: ["family", "general"],
    stageTags: ["jianghuai-expansion"],
    homeCityNodeId: "settlement.yangzhou_province",
    currentCityNodeId: "settlement.yangzhou_province",
    shortBio: "张士诚宗族人物。",
    gameplayUse: "张氏府邸与军府补位。",
    cityNpcProfile: cityNpcProfile({ title: "张氏宗族", personality: "保守", specialty: "府务" }),
    leaderResidenceProfile: militaryResidence("宗族将领", "张士诚周"),
  }),
  character({
    id: "zyz.character.ye_dexin",
    canonicalName: "叶德新",
    sourceType: "historical",
    priority: "P2",
    gender: "male",
    factionId: "zhang_shicheng",
    factionName: "张士诚周",
    roleTags: ["civil-official"],
    stageTags: ["late-context-only"],
    homeCityNodeId: "settlement.suzhou_province",
    currentCityNodeId: "settlement.suzhou_province",
    shortBio: "张士诚周政权文臣。",
    gameplayUse: "平江政务、文书和府邸顾问。",
    cityNpcProfile: cityNpcProfile({ title: "右丞相", personality: "圆滑", specialty: "政务" }),
    leaderResidenceProfile: advisorResidence("中书右丞相", "张士诚周"),
  }),
  character({
    id: "zyz.character.chen_ji",
    canonicalName: "陈基",
    sourceType: "historical",
    priority: "P2",
    gender: "male",
    factionId: "zhang_shicheng",
    factionName: "张士诚周",
    roleTags: ["civil-official", "advisor"],
    stageTags: ["late-context-only"],
    homeCityNodeId: "settlement.suzhou_province",
    currentCityNodeId: "settlement.suzhou_province",
    shortBio: "张士诚阵营文臣。",
    gameplayUse: "江南文官府邸和文人事件。",
    cityNpcProfile: cityNpcProfile({ title: "内史", personality: "清介", specialty: "文书" }),
    leaderResidenceProfile: advisorResidence("内史", "张士诚周"),
  }),
  character({
    id: "zyz.character.shi_naian",
    canonicalName: "施耐庵",
    sourceType: "uncertain",
    priority: "P3",
    gender: "male",
    factionId: "zhang_shicheng",
    factionName: "张士诚周",
    roleTags: ["advisor", "rumor-source"],
    stageTags: ["late-context-only"],
    homeCityNodeId: "settlement.suzhou_province",
    currentCityNodeId: "settlement.suzhou_province",
    shortBio: "文学化候选人物，需作为传闻/演绎而非硬史实处理。",
    gameplayUse: "江南文人传闻、说书与文本事件。",
    sourceNotes: ["项目演绎候选，史实归属需谨慎。"],
    cityNpcProfile: cityNpcProfile({ title: "说书文士", personality: "疏狂", specialty: "传闻" }),
  }),
  character({
    id: "zyz.character.chen_li",
    canonicalName: "陈理",
    sourceType: "historical",
    priority: "P1",
    gender: "male",
    birthYear: 1351,
    deathYear: 1408,
    factionId: "chen_youliang",
    factionName: "陈友谅汉",
    roleTags: ["family", "event-only"],
    stageTags: ["late-context-only"],
    homeCityNodeId: "settlement.wuchang_province",
    currentCityNodeId: "settlement.wuchang_province",
    shortBio: "陈友谅之子，陈汉后续政权人物。",
    gameplayUse: "陈汉继承与后续降服事件。",
    cityNpcProfile: cityNpcProfile({ title: "德寿王", personality: "稚弱", specialty: "宗族" }),
  }),
  character({
    id: "zyz.character.zhang_bixian",
    canonicalName: "张必先",
    sourceType: "historical",
    priority: "P1",
    gender: "male",
    factionId: "chen_youliang",
    factionName: "陈友谅汉",
    roleTags: ["advisor", "civil-official"],
    stageTags: ["late-context-only"],
    homeCityNodeId: "settlement.wuchang_province",
    currentCityNodeId: "settlement.wuchang_province",
    shortBio: "陈汉高层人物。",
    gameplayUse: "陈汉府邸、军政决策线。",
    cityNpcProfile: cityNpcProfile({ title: "丞相", personality: "强硬", specialty: "军政" }),
    leaderResidenceProfile: advisorResidence("丞相", "陈友谅汉"),
  }),
  character({
    id: "zyz.character.hu_mei",
    canonicalName: "胡美",
    sourceType: "historical",
    priority: "P2",
    gender: "male",
    factionId: "chen_youliang",
    factionName: "陈友谅汉",
    roleTags: ["civil-official", "general"],
    stageTags: ["late-context-only"],
    homeCityNodeId: "settlement.nanchang_province",
    currentCityNodeId: "settlement.nanchang_province",
    shortBio: "陈汉江西方向人物。",
    gameplayUse: "江西守备与政务人物池。",
    cityNpcProfile: cityNpcProfile({ title: "江西丞相", personality: "老练", specialty: "守土" }),
    leaderResidenceProfile: advisorResidence("江西丞相", "陈友谅汉"),
  }),
  character({
    id: "zyz.character.luo_furen",
    canonicalName: "罗复仁",
    sourceType: "historical",
    priority: "P2",
    gender: "male",
    factionId: "chen_youliang",
    factionName: "陈友谅汉",
    roleTags: ["civil-official"],
    stageTags: ["late-context-only"],
    homeCityNodeId: "settlement.wuchang_province",
    currentCityNodeId: "settlement.wuchang_province",
    shortBio: "陈汉文臣候选。",
    gameplayUse: "陈汉府邸文官、劝降与政务支线。",
    cityNpcProfile: cityNpcProfile({ title: "吉水同知", personality: "清直", specialty: "政务" }),
    leaderResidenceProfile: advisorResidence("吉水同知", "陈友谅汉"),
  }),
  character({
    id: "zyz.character.ming_sheng",
    canonicalName: "明升",
    sourceType: "historical",
    priority: "P2",
    gender: "male",
    factionId: "ming_yuzhen",
    factionName: "明玉珍夏",
    roleTags: ["family"],
    stageTags: ["late-context-only"],
    homeCityNodeId: "settlement.chendu_province",
    currentCityNodeId: "settlement.chendu_province",
    shortBio: "明玉珍之子，夏政权继承人。",
    gameplayUse: "西南继承与外交线。",
    cityNpcProfile: cityNpcProfile({ title: "夏世子", personality: "年轻", specialty: "宗族" }),
  }),
  character({
    id: "zyz.character.dai_shou",
    canonicalName: "戴寿",
    sourceType: "historical",
    priority: "P2",
    gender: "male",
    factionId: "ming_yuzhen",
    factionName: "明玉珍夏",
    roleTags: ["civil-official", "general"],
    stageTags: ["late-context-only"],
    homeCityNodeId: "settlement.chendu_province",
    currentCityNodeId: "settlement.chendu_province",
    shortBio: "明玉珍夏政权四川方向人物。",
    gameplayUse: "成都府邸、四川政务和军务。",
    cityNpcProfile: cityNpcProfile({ title: "四川行省平章", personality: "持重", specialty: "川蜀政务" }),
    leaderResidenceProfile: advisorResidence("四川行省平章", "明玉珍夏"),
  }),
  character({
    id: "zyz.character.fang_guoying",
    canonicalName: "方国瑛",
    sourceType: "historical",
    priority: "P2",
    gender: "male",
    factionId: "fang_guozhen",
    factionName: "方国珍浙东",
    roleTags: ["family", "general"],
    stageTags: ["late-context-only"],
    homeCityNodeId: "settlement.ningbo_province",
    currentCityNodeId: "settlement.ningbo_province",
    shortBio: "方国珍宗族人物。",
    gameplayUse: "浙东海上势力府邸补位。",
    cityNpcProfile: cityNpcProfile({ title: "方氏宗族", personality: "谨慎", specialty: "海路" }),
    leaderResidenceProfile: militaryResidence("海上将领", "方国珍浙东"),
  }),
  character({
    id: "zyz.character.ni_keren",
    canonicalName: "倪克仁",
    sourceType: "historical",
    priority: "P2",
    gender: "male",
    factionId: "fang_guozhen",
    factionName: "方国珍浙东",
    roleTags: ["civil-official", "advisor"],
    stageTags: ["late-context-only"],
    homeCityNodeId: "settlement.ningbo_province",
    currentCityNodeId: "settlement.ningbo_province",
    shortBio: "浙东势力人物。",
    gameplayUse: "浙东府邸文官、海贸谈判。",
    cityNpcProfile: cityNpcProfile({ title: "幕僚", personality: "审慎", specialty: "海贸" }),
    leaderResidenceProfile: advisorResidence("幕僚", "方国珍浙东"),
  }),
  character({
    id: "zyz.character.chen_zonghai",
    canonicalName: "陈宗海",
    sourceType: "historical",
    priority: "P2",
    gender: "male",
    factionId: "chen_youding",
    factionName: "福建陈友定",
    roleTags: ["general"],
    stageTags: ["late-context-only"],
    homeCityNodeId: "settlement.fuzhou_province",
    currentCityNodeId: "settlement.fuzhou_province",
    shortBio: "陈友定阵营人物。",
    gameplayUse: "福建元军府邸补位。",
    cityNpcProfile: cityNpcProfile({ title: "福建将领", personality: "刚直", specialty: "守城" }),
    leaderResidenceProfile: militaryResidence("福建将领", "福建陈友定"),
  }),
  character({
    id: "zyz.character.zheng_ding",
    canonicalName: "郑定",
    sourceType: "historical",
    priority: "P2",
    gender: "male",
    factionId: "chen_youding",
    factionName: "福建陈友定",
    roleTags: ["civil-official"],
    stageTags: ["late-context-only"],
    homeCityNodeId: "settlement.fuzhou_province",
    currentCityNodeId: "settlement.fuzhou_province",
    shortBio: "福建陈友定阵营官员。",
    gameplayUse: "福建政务、粮道和海路事件。",
    cityNpcProfile: cityNpcProfile({ title: "福建官员", personality: "精细", specialty: "粮道" }),
    leaderResidenceProfile: advisorResidence("福建官员", "福建陈友定"),
  }),
  character({
    id: "zyz.character.hama",
    canonicalName: "哈麻",
    sourceType: "historical",
    priority: "P2",
    gender: "male",
    factionId: "yuan_court",
    factionName: "元廷中央",
    roleTags: ["civil-official"],
    stageTags: ["late-context-only"],
    homeCityNodeId: "settlement.shuntian_province",
    currentCityNodeId: "settlement.shuntian_province",
    shortBio: "元廷权臣。",
    gameplayUse: "大都政局和朝廷腐败背景。",
    cityNpcProfile: cityNpcProfile({ title: "权臣", personality: "阴鸷", specialty: "朝局" }),
    leaderResidenceProfile: advisorResidence("权臣", "元廷中央"),
  }),
  character({
    id: "zyz.character.guan_bao",
    canonicalName: "关保",
    sourceType: "historical",
    priority: "P2",
    gender: "male",
    factionId: "yuan_henan_shandong",
    factionName: "河南山东元军",
    roleTags: ["general", "enemy"],
    stageTags: ["late-context-only"],
    homeCityNodeId: "settlement.kaifeng_province",
    currentCityNodeId: "settlement.kaifeng_province",
    shortBio: "河南山东元军将领。",
    gameplayUse: "北方元军战斗池。",
    cityNpcProfile: cityNpcProfile({ title: "定远大将军", personality: "悍勇", specialty: "军阵" }),
    leaderResidenceProfile: militaryResidence("定远大将军", "河南山东元军"),
  }),
  character({
    id: "zyz.character.li_shichang",
    canonicalName: "李世昌",
    sourceType: "historical",
    priority: "P2",
    gender: "male",
    factionId: "yuan_shaanxi_gansu",
    factionName: "陕西甘肃元军",
    roleTags: ["general", "enemy"],
    stageTags: ["late-context-only"],
    homeCityNodeId: "settlement.gongchang_province",
    currentCityNodeId: "settlement.gongchang_province",
    shortBio: "李思齐势力将领。",
    gameplayUse: "巩昌元军府邸补位。",
    cityNpcProfile: cityNpcProfile({ title: "建威将军", personality: "谨严", specialty: "守备" }),
    leaderResidenceProfile: militaryResidence("建威将军", "陕西甘肃元军"),
  }),
  character({
    id: "zyz.character.baitemur",
    canonicalName: "拜帖木儿",
    sourceType: "historical",
    priority: "P2",
    gender: "male",
    factionId: "yuan_shaanxi_gansu",
    factionName: "陕西甘肃元军",
    roleTags: ["civil-official", "general"],
    stageTags: ["late-context-only"],
    homeCityNodeId: "settlement.gongchang_province",
    currentCityNodeId: "settlement.gongchang_province",
    shortBio: "西北元军宣慰同知。",
    gameplayUse: "西北政务与军府支线。",
    cityNpcProfile: cityNpcProfile({ title: "宣慰同知", personality: "圆融", specialty: "边政" }),
    leaderResidenceProfile: advisorResidence("宣慰同知", "陕西甘肃元军"),
  }),
];

const historicalCharacterProfileOverrides: Record<
  string,
  Pick<HistoricalCharacterRecord, "cityNpcProfile" | "leaderResidenceProfile">
> = {
  "zyz.character.guo_zixing": {
    cityNpcProfile: cityNpcProfile({ title: "红巾首领", personality: "多疑", specialty: "军府" }),
    leaderResidenceProfile: leaderResidenceProfile({
      role: "lord",
      title: "主帅",
      occupation: "红巾军首领",
      affiliationLabel: "濠州郭子兴集团",
      teachableSkillKeys: ["military", "rhetoric", "etiquette"],
    }),
  },
  "zyz.character.tang_he": {
    cityNpcProfile: cityNpcProfile({ title: "同乡武将", personality: "老成", specialty: "军务" }),
    leaderResidenceProfile: militaryResidence("宿将", "濠州军府"),
  },
  "zyz.character.xu_da": {
    cityNpcProfile: cityNpcProfile({ title: "前锋武将", personality: "沉稳", specialty: "统兵" }),
    leaderResidenceProfile: militaryResidence("前锋大将", "朱元璋军府"),
  },
  "zyz.character.li_shanchang": {
    cityNpcProfile: cityNpcProfile({ title: "乡贤", personality: "精细", specialty: "政务" }),
    leaderResidenceProfile: advisorResidence("幕僚", "朱元璋幕府"),
  },
};

export const zhuYuanzhangEarlyCharacters: HistoricalCharacterRecord[] = [
  ...zhuYuanzhangCoreCharacters,
  ...zhuYuanzhangAdditionalCharacters,
].map((record) => ({
  ...record,
  ...(historicalCharacterProfileOverrides[record.id] ?? {}),
}));

const zhuYuanzhangCoreCityRosters: HistoricalCityRoster[] = [
  {
    cityNodeId: "settlement.fenyang_province",
    primaryCharacterIds: [
      "zyz.character.zhu_yuanzhang",
      "zyz.character.guo_zixing",
      "zyz.character.ma_shi",
      "zyz.character.tang_he",
    ],
    secondaryCharacterIds: [
      "zyz.character.guo_tianxu",
      "zyz.character.zhang_tianyou",
      "zyz.character.sun_deya",
      "zyz.character.xu_da",
      "zyz.character.zhou_dexing",
      "zyz.character.guo_ying",
      "zyz.character.huangjue_abbot",
      "zyz.character.temple_senior_monk",
      "zyz.character.zhongli_elder",
    ],
    backgroundCharacterIds: [],
    notes: "朱元璋和尚时期和投军期主城，含皇觉寺、钟离、濠州军府。",
  },
  {
    cityNodeId: "settlement.tieling_province",
    primaryCharacterIds: [
      "zyz.character.han_liner",
      "zyz.character.liu_futong",
    ],
    secondaryCharacterIds: ["zyz.character.sheng_wenyu"],
    backgroundCharacterIds: ["zyz.character.bai_buxin"],
    notes: "安丰/小明王宋政权据点。",
  },
  {
    cityNodeId: "settlement.runing_province",
    primaryCharacterIds: ["zyz.character.liu_futong"],
    secondaryCharacterIds: [
      "zyz.character.han_shantong",
      "zyz.character.du_zundao",
      "zyz.character.bai_buxin",
    ],
    backgroundCharacterIds: [],
    notes: "汝宁红巾活动区，承接韩山童、刘福通线。",
  },
  {
    cityNodeId: "settlement.luzhou_province",
    primaryCharacterIds: [
      "zyz.character.li_shanchang",
      "zyz.character.feng_guoyong",
    ],
    secondaryCharacterIds: [
      "zyz.character.xu_da",
      "zyz.character.geng_bingwen",
      "zyz.character.li_wenzhong",
    ],
    backgroundCharacterIds: [],
    notes: "江淮枢纽，适合政务、粮秣和军政过渡任务。",
  },
  {
    cityNodeId: "settlement.anqing_province",
    primaryCharacterIds: ["zyz.character.deng_yu"],
    secondaryCharacterIds: ["zyz.character.tang_he"],
    backgroundCharacterIds: [],
    notes: "江淮西线通道。",
  },
  {
    cityNodeId: "settlement.taiping_province",
    primaryCharacterIds: [
      "zyz.character.hu_dahai",
      "zyz.character.hua_yun",
    ],
    secondaryCharacterIds: [
      "zyz.character.xu_da",
      "zyz.character.chang_yuchun",
    ],
    backgroundCharacterIds: [],
    notes: "朱元璋南下江南后的跳板，不在和尚期默认开放。",
  },
  {
    cityNodeId: "settlement.yingtian_province",
    primaryCharacterIds: ["zyz.character.zhu_yuanzhang"],
    secondaryCharacterIds: [
      "zyz.character.li_shanchang",
      "zyz.character.xu_da",
      "zyz.character.chang_yuchun",
    ],
    backgroundCharacterIds: [],
    notes: "集庆路/上元，后续攻取后成为核心城市。",
  },
  {
    cityNodeId: "settlement.huaian_province",
    primaryCharacterIds: ["zyz.character.zhang_shicheng"],
    secondaryCharacterIds: [
      "zyz.character.lv_zhen",
      "zyz.character.panyuan_shao",
    ],
    backgroundCharacterIds: [],
    notes: "高邮/淮东，张士诚早期势力范围。",
  },
  {
    cityNodeId: "settlement.yangzhou_province",
    primaryCharacterIds: ["zyz.character.zhang_shicheng"],
    secondaryCharacterIds: [
      "zyz.character.zhang_shide",
      "zyz.character.li_bosheng",
      "zyz.character.rao_jie",
    ],
    backgroundCharacterIds: [],
    notes: "张士诚淮东竞争线。",
  },
  {
    cityNodeId: "settlement.suzhou_province",
    primaryCharacterIds: ["zyz.character.zhang_shixin"],
    secondaryCharacterIds: ["zyz.character.zhang_shicheng"],
    backgroundCharacterIds: [],
    notes: "平江/苏州，张士诚后期江南核心。",
  },
  {
    cityNodeId: "settlement.wuchang_province",
    primaryCharacterIds: [
      "zyz.character.chen_youliang",
      "zyz.character.zhang_dingbian",
    ],
    secondaryCharacterIds: [
      "zyz.character.xu_shouhui",
      "zyz.character.zou_pusheng",
    ],
    backgroundCharacterIds: [],
    notes: "陈友谅、天完/陈汉线。",
  },
  {
    cityNodeId: "settlement.nanchang_province",
    primaryCharacterIds: ["zyz.character.zhu_wenzheng"],
    secondaryCharacterIds: [
      "zyz.character.feng_sheng",
      "zyz.character.chen_youliang",
    ],
    backgroundCharacterIds: [],
    notes: "洪都/南昌，后续守城和陈汉压力线。",
  },
  {
    cityNodeId: "settlement.chongqing_province",
    primaryCharacterIds: ["zyz.character.ming_yuzhen"],
    secondaryCharacterIds: ["zyz.character.wan_sheng"],
    backgroundCharacterIds: [],
    notes: "明玉珍夏政权西南据点。",
  },
  {
    cityNodeId: "settlement.chendu_province",
    primaryCharacterIds: ["zyz.character.ming_yuzhen"],
    secondaryCharacterIds: [],
    backgroundCharacterIds: [],
    notes: "四川夏政权范围。",
  },
  {
    cityNodeId: "settlement.ningbo_province",
    primaryCharacterIds: ["zyz.character.fang_guozhen"],
    secondaryCharacterIds: [],
    backgroundCharacterIds: [],
    notes: "方国珍浙东海上势力。",
  },
  {
    cityNodeId: "settlement.wenzhou_province",
    primaryCharacterIds: ["zyz.character.fang_li"],
    secondaryCharacterIds: ["zyz.character.fang_guozhen"],
    backgroundCharacterIds: [],
    notes: "方国珍浙东支线。",
  },
  {
    cityNodeId: "settlement.fuzhou_province",
    primaryCharacterIds: ["zyz.character.chen_youding"],
    secondaryCharacterIds: [],
    backgroundCharacterIds: [],
    notes: "福建陈友定元军线。",
  },
  {
    cityNodeId: "settlement.shuntian_province",
    primaryCharacterIds: ["zyz.character.toghon_temur"],
    secondaryCharacterIds: ["zyz.character.ayushiridara"],
    backgroundCharacterIds: [],
    notes: "大都元廷中央。",
  },
  {
    cityNodeId: "settlement.kaifeng_province",
    primaryCharacterIds: [
      "zyz.character.chaghan_temur",
      "zyz.character.koketumur",
    ],
    secondaryCharacterIds: [],
    backgroundCharacterIds: [],
    notes: "河南元军压力线。",
  },
  {
    cityNodeId: "settlement.gongchang_province",
    primaryCharacterIds: ["zyz.character.li_siqi"],
    secondaryCharacterIds: [],
    backgroundCharacterIds: [],
    notes: "西北元军李思齐势力。",
  },
  {
    cityNodeId: "settlement.xian_province",
    primaryCharacterIds: ["zyz.character.zhang_liangbi"],
    secondaryCharacterIds: [],
    backgroundCharacterIds: [],
    notes: "陕西张良弼势力。",
  },
];

const zhuYuanzhangCityRosterAdditions: HistoricalCityRoster[] = [
  {
    cityNodeId: "settlement.fenyang_province",
    primaryCharacterIds: [],
    secondaryCharacterIds: ["zyz.character.guo_xing"],
    backgroundCharacterIds: [
      "zyz.character.haozhou_salt_runner",
      "zyz.character.haozhou_red_turban_scout",
    ],
    notes: "补充濠州基层城市池和亲军候选。",
  },
  {
    cityNodeId: "settlement.luzhou_province",
    primaryCharacterIds: [],
    secondaryCharacterIds: [
      "zyz.character.miao_daheng",
      "zyz.character.ding_pulang",
    ],
    backgroundCharacterIds: ["zyz.character.hu_weiyong"],
    notes: "补充江淮幕府、军府和文书候选。",
  },
  {
    cityNodeId: "settlement.yingtian_province",
    primaryCharacterIds: ["zyz.character.liu_ji"],
    secondaryCharacterIds: [
      "zyz.character.song_lian",
      "zyz.character.zhu_sheng",
      "zyz.character.mu_ying",
      "zyz.character.fu_youdej",
      "zyz.character.hu_weiyong",
      "zyz.character.lan_yu",
    ],
    backgroundCharacterIds: [],
    notes: "补充后续应天幕府、史馆、亲军和将领府邸候选。",
  },
  {
    cityNodeId: "settlement.tieling_province",
    primaryCharacterIds: [],
    secondaryCharacterIds: ["zyz.character.han_tong"],
    backgroundCharacterIds: [],
    notes: "补充小明王宗族背景。",
  },
  {
    cityNodeId: "settlement.kaifeng_province",
    primaryCharacterIds: [],
    secondaryCharacterIds: [
      "zyz.character.tian_feng",
      "zyz.character.wang_shicheng_song",
    ],
    backgroundCharacterIds: [],
    notes: "补充北方宋线和河南战报人物。",
  },
  {
    cityNodeId: "settlement.yangzhou_province",
    primaryCharacterIds: [],
    secondaryCharacterIds: [
      "zyz.character.zhang_tianyou_zhou",
      "zyz.character.zhang_shiyi",
    ],
    backgroundCharacterIds: [],
    notes: "补充张士诚宗族与扬州府邸候选。",
  },
  {
    cityNodeId: "settlement.suzhou_province",
    primaryCharacterIds: [],
    secondaryCharacterIds: [
      "zyz.character.ye_dexin",
      "zyz.character.chen_ji",
    ],
    backgroundCharacterIds: ["zyz.character.shi_naian"],
    notes: "补充平江文官、文人和府邸候选。",
  },
  {
    cityNodeId: "settlement.wuchang_province",
    primaryCharacterIds: [],
    secondaryCharacterIds: [
      "zyz.character.chen_li",
      "zyz.character.zhang_bixian",
      "zyz.character.luo_furen",
    ],
    backgroundCharacterIds: [],
    notes: "补充陈汉宗族、丞相和文臣候选。",
  },
  {
    cityNodeId: "settlement.nanchang_province",
    primaryCharacterIds: [],
    secondaryCharacterIds: ["zyz.character.hu_mei"],
    backgroundCharacterIds: [],
    notes: "补充江西方向陈汉人物。",
  },
  {
    cityNodeId: "settlement.chendu_province",
    primaryCharacterIds: [],
    secondaryCharacterIds: [
      "zyz.character.ming_sheng",
      "zyz.character.dai_shou",
    ],
    backgroundCharacterIds: [],
    notes: "补充夏政权继承人与成都府邸人物。",
  },
  {
    cityNodeId: "settlement.ningbo_province",
    primaryCharacterIds: [],
    secondaryCharacterIds: [
      "zyz.character.fang_guoying",
      "zyz.character.ni_keren",
    ],
    backgroundCharacterIds: [],
    notes: "补充浙东海上势力府邸人物。",
  },
  {
    cityNodeId: "settlement.fuzhou_province",
    primaryCharacterIds: [],
    secondaryCharacterIds: [
      "zyz.character.chen_zonghai",
      "zyz.character.zheng_ding",
    ],
    backgroundCharacterIds: [],
    notes: "补充福建陈友定府邸人物。",
  },
  {
    cityNodeId: "settlement.shuntian_province",
    primaryCharacterIds: [],
    secondaryCharacterIds: ["zyz.character.hama"],
    backgroundCharacterIds: [],
    notes: "补充元廷朝局人物。",
  },
  {
    cityNodeId: "settlement.kaifeng_province",
    primaryCharacterIds: [],
    secondaryCharacterIds: ["zyz.character.guan_bao"],
    backgroundCharacterIds: [],
    notes: "补充河南山东元军府邸候选。",
  },
  {
    cityNodeId: "settlement.gongchang_province",
    primaryCharacterIds: [],
    secondaryCharacterIds: [
      "zyz.character.li_shichang",
      "zyz.character.baitemur",
    ],
    backgroundCharacterIds: [],
    notes: "补充西北元军府邸候选。",
  },
];

function uniqueIds(ids: string[]): string[] {
  return [...new Set(ids)];
}

function mergeCityRoster(
  baseRoster: HistoricalCityRoster,
  addition: HistoricalCityRoster
): HistoricalCityRoster {
  return {
    cityNodeId: baseRoster.cityNodeId,
    primaryCharacterIds: uniqueIds([
      ...baseRoster.primaryCharacterIds,
      ...addition.primaryCharacterIds,
    ]),
    secondaryCharacterIds: uniqueIds([
      ...baseRoster.secondaryCharacterIds,
      ...addition.secondaryCharacterIds,
    ]),
    backgroundCharacterIds: uniqueIds([
      ...baseRoster.backgroundCharacterIds,
      ...addition.backgroundCharacterIds,
    ]),
    notes: `${baseRoster.notes} ${addition.notes}`.trim(),
  };
}

export const zhuYuanzhangCityRosters: HistoricalCityRoster[] = [
  ...zhuYuanzhangCoreCityRosters,
];

for (const addition of zhuYuanzhangCityRosterAdditions) {
  const existingIndex = zhuYuanzhangCityRosters.findIndex(
    (roster) => roster.cityNodeId === addition.cityNodeId
  );
  if (existingIndex >= 0) {
    const existingRoster = zhuYuanzhangCityRosters[existingIndex];
    if (existingRoster != null) {
      zhuYuanzhangCityRosters[existingIndex] = mergeCityRoster(
        existingRoster,
        addition
      );
    }
  } else {
    zhuYuanzhangCityRosters.push(addition);
  }
}

export function selectHistoricalCharactersForCity(
  cityNodeId: string
): HistoricalCharacterRecord[] {
  return zhuYuanzhangEarlyCharacters.filter(
    (characterRecord) =>
      characterRecord.currentCityNodeId === cityNodeId ||
      characterRecord.homeCityNodeId === cityNodeId ||
      characterRecord.relatedCityNodeIds.includes(cityNodeId)
  );
}

export function selectCityNpcEligibleHistoricalCharacters(
  cityNodeId: string
): HistoricalCharacterRecord[] {
  return selectHistoricalCharactersForCity(cityNodeId).filter(
    (characterRecord) => characterRecord.cityNpcProfile?.enabled === true
  );
}

export function selectLeaderResidenceEligibleHistoricalCharacters(
  cityNodeId: string
): HistoricalCharacterRecord[] {
  return selectHistoricalCharactersForCity(cityNodeId).filter(
    (characterRecord) =>
      characterRecord.leaderResidenceProfile?.eligible === true
  );
}
